#include "RootLua.hpp"
#include <sol/sol.hpp>
#include "src/autoconfig/Root.hpp"

void LuaAuto::BindRootConfig_0(sol::state& lua)
{
    lua.new_usertype<countryUSA>("countryUSA",
        "country_name", &countryUSA::country_name,
        "year", &countryUSA::year,
        "capital", &countryUSA::capital,
        "currency", &countryUSA::currency,
        "states", &countryUSA::states,
        "states_min", &countryUSA::states_min,
        "states_max", &countryUSA::states_max,
        "states_norm", &countryUSA::states_norm,
        "states_sigmoid", &countryUSA::states_sigmoid,
        "territories", &countryUSA::territories,
        "territories_min", &countryUSA::territories_min,
        "territories_max", &countryUSA::territories_max,
        "territories_norm", &countryUSA::territories_norm,
        "territories_sigmoid", &countryUSA::territories_sigmoid,
        "time_zones", &countryUSA::time_zones,
        "time_zones_min", &countryUSA::time_zones_min,
        "time_zones_max", &countryUSA::time_zones_max,
        "time_zones_norm", &countryUSA::time_zones_norm,
        "time_zones_sigmoid", &countryUSA::time_zones_sigmoid
    );

    lua.new_usertype<resources_HighBest_sigmoid_result_Part02USA>("resources_HighBest_sigmoid_result_Part02USA",
        "farmland_million_acres", &resources_HighBest_sigmoid_result_Part02USA::farmland_million_acres,
        "farmland_million_acres_min", &resources_HighBest_sigmoid_result_Part02USA::farmland_million_acres_min,
        "farmland_million_acres_max", &resources_HighBest_sigmoid_result_Part02USA::farmland_million_acres_max,
        "farmland_million_acres_norm", &resources_HighBest_sigmoid_result_Part02USA::farmland_million_acres_norm,
        "farmland_million_acres_sigmoid", &resources_HighBest_sigmoid_result_Part02USA::farmland_million_acres_sigmoid
    );

    lua.new_usertype<resources_LowBest_sigmoid_resultUSA>("resources_LowBest_sigmoid_resultUSA",
        "freshwater_withdrawal_bcm", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm,
        "freshwater_withdrawal_bcm_min", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm_min,
        "freshwater_withdrawal_bcm_max", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm_max,
        "freshwater_withdrawal_bcm_norm", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm_norm,
        "freshwater_withdrawal_bcm_sigmoid", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm_sigmoid,
        "co2_emissions_mt", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt,
        "co2_emissions_mt_min", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt_min,
        "co2_emissions_mt_max", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt_max,
        "co2_emissions_mt_norm", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt_norm,
        "co2_emissions_mt_sigmoid", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt_sigmoid
    );

    lua.new_usertype<infrastructure_HighBest_sigmoid_result_Part01USA>("infrastructure_HighBest_sigmoid_result_Part01USA",
        "land_area_km2", &infrastructure_HighBest_sigmoid_result_Part01USA::land_area_km2,
        "land_area_km2_min", &infrastructure_HighBest_sigmoid_result_Part01USA::land_area_km2_min,
        "land_area_km2_max", &infrastructure_HighBest_sigmoid_result_Part01USA::land_area_km2_max,
        "land_area_km2_norm", &infrastructure_HighBest_sigmoid_result_Part01USA::land_area_km2_norm,
        "land_area_km2_sigmoid", &infrastructure_HighBest_sigmoid_result_Part01USA::land_area_km2_sigmoid,
        "total_area_km2", &infrastructure_HighBest_sigmoid_result_Part01USA::total_area_km2,
        "total_area_km2_min", &infrastructure_HighBest_sigmoid_result_Part01USA::total_area_km2_min,
        "total_area_km2_max", &infrastructure_HighBest_sigmoid_result_Part01USA::total_area_km2_max,
        "total_area_km2_norm", &infrastructure_HighBest_sigmoid_result_Part01USA::total_area_km2_norm,
        "total_area_km2_sigmoid", &infrastructure_HighBest_sigmoid_result_Part01USA::total_area_km2_sigmoid,
        "coastline_km", &infrastructure_HighBest_sigmoid_result_Part01USA::coastline_km,
        "coastline_km_min", &infrastructure_HighBest_sigmoid_result_Part01USA::coastline_km_min,
        "coastline_km_max", &infrastructure_HighBest_sigmoid_result_Part01USA::coastline_km_max,
        "coastline_km_norm", &infrastructure_HighBest_sigmoid_result_Part01USA::coastline_km_norm,
        "coastline_km_sigmoid", &infrastructure_HighBest_sigmoid_result_Part01USA::coastline_km_sigmoid,
        "road_km", &infrastructure_HighBest_sigmoid_result_Part01USA::road_km,
        "road_km_min", &infrastructure_HighBest_sigmoid_result_Part01USA::road_km_min,
        "road_km_max", &infrastructure_HighBest_sigmoid_result_Part01USA::road_km_max,
        "road_km_norm", &infrastructure_HighBest_sigmoid_result_Part01USA::road_km_norm,
        "road_km_sigmoid", &infrastructure_HighBest_sigmoid_result_Part01USA::road_km_sigmoid,
        "rail_km", &infrastructure_HighBest_sigmoid_result_Part01USA::rail_km,
        "rail_km_min", &infrastructure_HighBest_sigmoid_result_Part01USA::rail_km_min,
        "rail_km_max", &infrastructure_HighBest_sigmoid_result_Part01USA::rail_km_max,
        "rail_km_norm", &infrastructure_HighBest_sigmoid_result_Part01USA::rail_km_norm,
        "rail_km_sigmoid", &infrastructure_HighBest_sigmoid_result_Part01USA::rail_km_sigmoid,
        "airports", &infrastructure_HighBest_sigmoid_result_Part01USA::airports,
        "airports_min", &infrastructure_HighBest_sigmoid_result_Part01USA::airports_min,
        "airports_max", &infrastructure_HighBest_sigmoid_result_Part01USA::airports_max,
        "airports_norm", &infrastructure_HighBest_sigmoid_result_Part01USA::airports_norm,
        "airports_sigmoid", &infrastructure_HighBest_sigmoid_result_Part01USA::airports_sigmoid,
        "major_ports", &infrastructure_HighBest_sigmoid_result_Part01USA::major_ports,
        "major_ports_min", &infrastructure_HighBest_sigmoid_result_Part01USA::major_ports_min,
        "major_ports_max", &infrastructure_HighBest_sigmoid_result_Part01USA::major_ports_max,
        "major_ports_norm", &infrastructure_HighBest_sigmoid_result_Part01USA::major_ports_norm,
        "major_ports_sigmoid", &infrastructure_HighBest_sigmoid_result_Part01USA::major_ports_sigmoid,
        "electricity_access_pct", &infrastructure_HighBest_sigmoid_result_Part01USA::electricity_access_pct,
        "electricity_access_pct_min", &infrastructure_HighBest_sigmoid_result_Part01USA::electricity_access_pct_min,
        "electricity_access_pct_max", &infrastructure_HighBest_sigmoid_result_Part01USA::electricity_access_pct_max,
        "electricity_access_pct_norm", &infrastructure_HighBest_sigmoid_result_Part01USA::electricity_access_pct_norm,
        "electricity_access_pct_sigmoid", &infrastructure_HighBest_sigmoid_result_Part01USA::electricity_access_pct_sigmoid,
        "safe_water_access_pct", &infrastructure_HighBest_sigmoid_result_Part01USA::safe_water_access_pct,
        "safe_water_access_pct_min", &infrastructure_HighBest_sigmoid_result_Part01USA::safe_water_access_pct_min,
        "safe_water_access_pct_max", &infrastructure_HighBest_sigmoid_result_Part01USA::safe_water_access_pct_max,
        "safe_water_access_pct_norm", &infrastructure_HighBest_sigmoid_result_Part01USA::safe_water_access_pct_norm,
        "safe_water_access_pct_sigmoid", &infrastructure_HighBest_sigmoid_result_Part01USA::safe_water_access_pct_sigmoid,
        "fixed_broadband_subscriptions", &infrastructure_HighBest_sigmoid_result_Part01USA::fixed_broadband_subscriptions,
        "fixed_broadband_subscriptions_min", &infrastructure_HighBest_sigmoid_result_Part01USA::fixed_broadband_subscriptions_min,
        "fixed_broadband_subscriptions_max", &infrastructure_HighBest_sigmoid_result_Part01USA::fixed_broadband_subscriptions_max,
        "fixed_broadband_subscriptions_norm", &infrastructure_HighBest_sigmoid_result_Part01USA::fixed_broadband_subscriptions_norm,
        "fixed_broadband_subscriptions_sigmoid", &infrastructure_HighBest_sigmoid_result_Part01USA::fixed_broadband_subscriptions_sigmoid
    );

    lua.new_usertype<infrastructure_HighBest_sigmoid_result_Part02USA>("infrastructure_HighBest_sigmoid_result_Part02USA",
        "mobile_subscriptions", &infrastructure_HighBest_sigmoid_result_Part02USA::mobile_subscriptions,
        "mobile_subscriptions_min", &infrastructure_HighBest_sigmoid_result_Part02USA::mobile_subscriptions_min,
        "mobile_subscriptions_max", &infrastructure_HighBest_sigmoid_result_Part02USA::mobile_subscriptions_max,
        "mobile_subscriptions_norm", &infrastructure_HighBest_sigmoid_result_Part02USA::mobile_subscriptions_norm,
        "mobile_subscriptions_sigmoid", &infrastructure_HighBest_sigmoid_result_Part02USA::mobile_subscriptions_sigmoid,
        "housing_units", &infrastructure_HighBest_sigmoid_result_Part02USA::housing_units,
        "housing_units_min", &infrastructure_HighBest_sigmoid_result_Part02USA::housing_units_min,
        "housing_units_max", &infrastructure_HighBest_sigmoid_result_Part02USA::housing_units_max,
        "housing_units_norm", &infrastructure_HighBest_sigmoid_result_Part02USA::housing_units_norm,
        "housing_units_sigmoid", &infrastructure_HighBest_sigmoid_result_Part02USA::housing_units_sigmoid,
        "data_centers", &infrastructure_HighBest_sigmoid_result_Part02USA::data_centers,
        "data_centers_min", &infrastructure_HighBest_sigmoid_result_Part02USA::data_centers_min,
        "data_centers_max", &infrastructure_HighBest_sigmoid_result_Part02USA::data_centers_max,
        "data_centers_norm", &infrastructure_HighBest_sigmoid_result_Part02USA::data_centers_norm,
        "data_centers_sigmoid", &infrastructure_HighBest_sigmoid_result_Part02USA::data_centers_sigmoid
    );

    lua.new_usertype<education_HighBest_sigmoid_resultUSA>("education_HighBest_sigmoid_resultUSA",
        "literacy_rate", &education_HighBest_sigmoid_resultUSA::literacy_rate,
        "literacy_rate_min", &education_HighBest_sigmoid_resultUSA::literacy_rate_min,
        "literacy_rate_max", &education_HighBest_sigmoid_resultUSA::literacy_rate_max,
        "literacy_rate_norm", &education_HighBest_sigmoid_resultUSA::literacy_rate_norm,
        "literacy_rate_sigmoid", &education_HighBest_sigmoid_resultUSA::literacy_rate_sigmoid,
        "education_spending_pct_gdp", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp,
        "education_spending_pct_gdp_min", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp_min,
        "education_spending_pct_gdp_max", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp_max,
        "education_spending_pct_gdp_norm", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp_norm,
        "education_spending_pct_gdp_sigmoid", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp_sigmoid,
        "school_life_expectancy", &education_HighBest_sigmoid_resultUSA::school_life_expectancy,
        "school_life_expectancy_min", &education_HighBest_sigmoid_resultUSA::school_life_expectancy_min,
        "school_life_expectancy_max", &education_HighBest_sigmoid_resultUSA::school_life_expectancy_max,
        "school_life_expectancy_norm", &education_HighBest_sigmoid_resultUSA::school_life_expectancy_norm,
        "school_life_expectancy_sigmoid", &education_HighBest_sigmoid_resultUSA::school_life_expectancy_sigmoid,
        "high_school_graduation_rate", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate,
        "high_school_graduation_rate_min", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate_min,
        "high_school_graduation_rate_max", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate_max,
        "high_school_graduation_rate_norm", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate_norm,
        "high_school_graduation_rate_sigmoid", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate_sigmoid,
        "tertiary_attainment_pct", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct,
        "tertiary_attainment_pct_min", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct_min,
        "tertiary_attainment_pct_max", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct_max,
        "tertiary_attainment_pct_norm", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct_norm,
        "tertiary_attainment_pct_sigmoid", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct_sigmoid,
        "public_school_students", &education_HighBest_sigmoid_resultUSA::public_school_students,
        "public_school_students_min", &education_HighBest_sigmoid_resultUSA::public_school_students_min,
        "public_school_students_max", &education_HighBest_sigmoid_resultUSA::public_school_students_max,
        "public_school_students_norm", &education_HighBest_sigmoid_resultUSA::public_school_students_norm,
        "public_school_students_sigmoid", &education_HighBest_sigmoid_resultUSA::public_school_students_sigmoid,
        "college_students", &education_HighBest_sigmoid_resultUSA::college_students,
        "college_students_min", &education_HighBest_sigmoid_resultUSA::college_students_min,
        "college_students_max", &education_HighBest_sigmoid_resultUSA::college_students_max,
        "college_students_norm", &education_HighBest_sigmoid_resultUSA::college_students_norm,
        "college_students_sigmoid", &education_HighBest_sigmoid_resultUSA::college_students_sigmoid,
        "stem_graduates_yearly", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly,
        "stem_graduates_yearly_min", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly_min,
        "stem_graduates_yearly_max", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly_max,
        "stem_graduates_yearly_norm", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly_norm,
        "stem_graduates_yearly_sigmoid", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly_sigmoid
    );

    lua.new_usertype<health_HighBest_sigmoid_resultUSA>("health_HighBest_sigmoid_resultUSA",
        "health_spending_pct_gdp", &health_HighBest_sigmoid_resultUSA::health_spending_pct_gdp,
        "health_spending_pct_gdp_min", &health_HighBest_sigmoid_resultUSA::health_spending_pct_gdp_min,
        "health_spending_pct_gdp_max", &health_HighBest_sigmoid_resultUSA::health_spending_pct_gdp_max,
        "health_spending_pct_gdp_norm", &health_HighBest_sigmoid_resultUSA::health_spending_pct_gdp_norm,
        "health_spending_pct_gdp_sigmoid", &health_HighBest_sigmoid_resultUSA::health_spending_pct_gdp_sigmoid,
        "insured_rate", &health_HighBest_sigmoid_resultUSA::insured_rate,
        "insured_rate_min", &health_HighBest_sigmoid_resultUSA::insured_rate_min,
        "insured_rate_max", &health_HighBest_sigmoid_resultUSA::insured_rate_max,
        "insured_rate_norm", &health_HighBest_sigmoid_resultUSA::insured_rate_norm,
        "insured_rate_sigmoid", &health_HighBest_sigmoid_resultUSA::insured_rate_sigmoid,
        "physicians_per_1000", &health_HighBest_sigmoid_resultUSA::physicians_per_1000,
        "physicians_per_1000_min", &health_HighBest_sigmoid_resultUSA::physicians_per_1000_min,
        "physicians_per_1000_max", &health_HighBest_sigmoid_resultUSA::physicians_per_1000_max,
        "physicians_per_1000_norm", &health_HighBest_sigmoid_resultUSA::physicians_per_1000_norm,
        "physicians_per_1000_sigmoid", &health_HighBest_sigmoid_resultUSA::physicians_per_1000_sigmoid,
        "hospital_beds_per_1000", &health_HighBest_sigmoid_resultUSA::hospital_beds_per_1000,
        "hospital_beds_per_1000_min", &health_HighBest_sigmoid_resultUSA::hospital_beds_per_1000_min,
        "hospital_beds_per_1000_max", &health_HighBest_sigmoid_resultUSA::hospital_beds_per_1000_max,
        "hospital_beds_per_1000_norm", &health_HighBest_sigmoid_resultUSA::hospital_beds_per_1000_norm,
        "hospital_beds_per_1000_sigmoid", &health_HighBest_sigmoid_resultUSA::hospital_beds_per_1000_sigmoid,
        "nurses", &health_HighBest_sigmoid_resultUSA::nurses,
        "nurses_min", &health_HighBest_sigmoid_resultUSA::nurses_min,
        "nurses_max", &health_HighBest_sigmoid_resultUSA::nurses_max,
        "nurses_norm", &health_HighBest_sigmoid_resultUSA::nurses_norm,
        "nurses_sigmoid", &health_HighBest_sigmoid_resultUSA::nurses_sigmoid,
        "hospital_count", &health_HighBest_sigmoid_resultUSA::hospital_count,
        "hospital_count_min", &health_HighBest_sigmoid_resultUSA::hospital_count_min,
        "hospital_count_max", &health_HighBest_sigmoid_resultUSA::hospital_count_max,
        "hospital_count_norm", &health_HighBest_sigmoid_resultUSA::hospital_count_norm,
        "hospital_count_sigmoid", &health_HighBest_sigmoid_resultUSA::hospital_count_sigmoid
    );

    lua.new_usertype<health_LowBest_sigmoid_resultUSA>("health_LowBest_sigmoid_resultUSA",
        "obesity_rate", &health_LowBest_sigmoid_resultUSA::obesity_rate,
        "obesity_rate_min", &health_LowBest_sigmoid_resultUSA::obesity_rate_min,
        "obesity_rate_max", &health_LowBest_sigmoid_resultUSA::obesity_rate_max,
        "obesity_rate_norm", &health_LowBest_sigmoid_resultUSA::obesity_rate_norm,
        "obesity_rate_sigmoid", &health_LowBest_sigmoid_resultUSA::obesity_rate_sigmoid,
        "maternal_mortality", &health_LowBest_sigmoid_resultUSA::maternal_mortality,
        "maternal_mortality_min", &health_LowBest_sigmoid_resultUSA::maternal_mortality_min,
        "maternal_mortality_max", &health_LowBest_sigmoid_resultUSA::maternal_mortality_max,
        "maternal_mortality_norm", &health_LowBest_sigmoid_resultUSA::maternal_mortality_norm,
        "maternal_mortality_sigmoid", &health_LowBest_sigmoid_resultUSA::maternal_mortality_sigmoid
    );

    lua.new_usertype<technology_HighBest_sigmoid_resultUSA>("technology_HighBest_sigmoid_resultUSA",
        "rnd_spending", &technology_HighBest_sigmoid_resultUSA::rnd_spending,
        "rnd_spending_min", &technology_HighBest_sigmoid_resultUSA::rnd_spending_min,
        "rnd_spending_max", &technology_HighBest_sigmoid_resultUSA::rnd_spending_max,
        "rnd_spending_norm", &technology_HighBest_sigmoid_resultUSA::rnd_spending_norm,
        "rnd_spending_sigmoid", &technology_HighBest_sigmoid_resultUSA::rnd_spending_sigmoid,
        "rnd_share_gdp", &technology_HighBest_sigmoid_resultUSA::rnd_share_gdp,
        "rnd_share_gdp_min", &technology_HighBest_sigmoid_resultUSA::rnd_share_gdp_min,
        "rnd_share_gdp_max", &technology_HighBest_sigmoid_resultUSA::rnd_share_gdp_max,
        "rnd_share_gdp_norm", &technology_HighBest_sigmoid_resultUSA::rnd_share_gdp_norm,
        "rnd_share_gdp_sigmoid", &technology_HighBest_sigmoid_resultUSA::rnd_share_gdp_sigmoid,
        "internet_users_pct", &technology_HighBest_sigmoid_resultUSA::internet_users_pct,
        "internet_users_pct_min", &technology_HighBest_sigmoid_resultUSA::internet_users_pct_min,
        "internet_users_pct_max", &technology_HighBest_sigmoid_resultUSA::internet_users_pct_max,
        "internet_users_pct_norm", &technology_HighBest_sigmoid_resultUSA::internet_users_pct_norm,
        "internet_users_pct_sigmoid", &technology_HighBest_sigmoid_resultUSA::internet_users_pct_sigmoid,
        "smartphone_users_pct", &technology_HighBest_sigmoid_resultUSA::smartphone_users_pct,
        "smartphone_users_pct_min", &technology_HighBest_sigmoid_resultUSA::smartphone_users_pct_min,
        "smartphone_users_pct_max", &technology_HighBest_sigmoid_resultUSA::smartphone_users_pct_max,
        "smartphone_users_pct_norm", &technology_HighBest_sigmoid_resultUSA::smartphone_users_pct_norm,
        "smartphone_users_pct_sigmoid", &technology_HighBest_sigmoid_resultUSA::smartphone_users_pct_sigmoid,
        "cloud_market_size", &technology_HighBest_sigmoid_resultUSA::cloud_market_size,
        "cloud_market_size_min", &technology_HighBest_sigmoid_resultUSA::cloud_market_size_min,
        "cloud_market_size_max", &technology_HighBest_sigmoid_resultUSA::cloud_market_size_max,
        "cloud_market_size_norm", &technology_HighBest_sigmoid_resultUSA::cloud_market_size_norm,
        "cloud_market_size_sigmoid", &technology_HighBest_sigmoid_resultUSA::cloud_market_size_sigmoid,
        "ai_private_investment", &technology_HighBest_sigmoid_resultUSA::ai_private_investment,
        "ai_private_investment_min", &technology_HighBest_sigmoid_resultUSA::ai_private_investment_min,
        "ai_private_investment_max", &technology_HighBest_sigmoid_resultUSA::ai_private_investment_max,
        "ai_private_investment_norm", &technology_HighBest_sigmoid_resultUSA::ai_private_investment_norm,
        "ai_private_investment_sigmoid", &technology_HighBest_sigmoid_resultUSA::ai_private_investment_sigmoid,
        "space_launches_yearly", &technology_HighBest_sigmoid_resultUSA::space_launches_yearly,
        "space_launches_yearly_min", &technology_HighBest_sigmoid_resultUSA::space_launches_yearly_min,
        "space_launches_yearly_max", &technology_HighBest_sigmoid_resultUSA::space_launches_yearly_max,
        "space_launches_yearly_norm", &technology_HighBest_sigmoid_resultUSA::space_launches_yearly_norm,
        "space_launches_yearly_sigmoid", &technology_HighBest_sigmoid_resultUSA::space_launches_yearly_sigmoid,
        "patents_granted_yearly", &technology_HighBest_sigmoid_resultUSA::patents_granted_yearly,
        "patents_granted_yearly_min", &technology_HighBest_sigmoid_resultUSA::patents_granted_yearly_min,
        "patents_granted_yearly_max", &technology_HighBest_sigmoid_resultUSA::patents_granted_yearly_max,
        "patents_granted_yearly_norm", &technology_HighBest_sigmoid_resultUSA::patents_granted_yearly_norm,
        "patents_granted_yearly_sigmoid", &technology_HighBest_sigmoid_resultUSA::patents_granted_yearly_sigmoid
    );

    lua.new_usertype<UtilityUSAConfig>("UtilityUSAConfig",
        "country", &UtilityUSAConfig::country,
        "resources_highbest_sigmoid_result_part02", &UtilityUSAConfig::resources_highbest_sigmoid_result_part02,
        "resources_lowbest_sigmoid_result", &UtilityUSAConfig::resources_lowbest_sigmoid_result,
        "infrastructure_highbest_sigmoid_result_part01", &UtilityUSAConfig::infrastructure_highbest_sigmoid_result_part01,
        "infrastructure_highbest_sigmoid_result_part02", &UtilityUSAConfig::infrastructure_highbest_sigmoid_result_part02,
        "education_highbest_sigmoid_result", &UtilityUSAConfig::education_highbest_sigmoid_result,
        "health_highbest_sigmoid_result", &UtilityUSAConfig::health_highbest_sigmoid_result,
        "health_lowbest_sigmoid_result", &UtilityUSAConfig::health_lowbest_sigmoid_result,
        "technology_highbest_sigmoid_result", &UtilityUSAConfig::technology_highbest_sigmoid_result
    );

}