#include "RootLua.hpp"
#include <sol/sol.hpp>
#include "src/autoconfig/Root.hpp"

void LuaAuto::BindRootConfig(sol::state& lua)
{
    lua.new_usertype<countryUSA>("countryUSA",
        "country_name", &countryUSA::country_name,
        "year", &countryUSA::year,
        "capital", &countryUSA::capital,
        "currency", &countryUSA::currency,
        "states", &countryUSA::states,
        "states_min", &countryUSA::states_min,
        "states_max", &countryUSA::states_max,
        "states_norm", &countryUSA::states_norm,
        "states_sigmoid", &countryUSA::states_sigmoid,
        "territories", &countryUSA::territories,
        "territories_min", &countryUSA::territories_min,
        "territories_max", &countryUSA::territories_max,
        "territories_norm", &countryUSA::territories_norm,
        "territories_sigmoid", &countryUSA::territories_sigmoid,
        "time_zones", &countryUSA::time_zones,
        "time_zones_min", &countryUSA::time_zones_min,
        "time_zones_max", &countryUSA::time_zones_max,
        "time_zones_norm", &countryUSA::time_zones_norm,
        "time_zones_sigmoid", &countryUSA::time_zones_sigmoid
    );

    lua.new_usertype<government_sigmoid_resultUSA>("government_sigmoid_resultUSA",
        "president", &government_sigmoid_resultUSA::president,
        "vice_president", &government_sigmoid_resultUSA::vice_president,
        "ruling_party", &government_sigmoid_resultUSA::ruling_party,
        "executive_departments", &government_sigmoid_resultUSA::executive_departments,
        "executive_departments_min", &government_sigmoid_resultUSA::executive_departments_min,
        "executive_departments_max", &government_sigmoid_resultUSA::executive_departments_max,
        "executive_departments_norm", &government_sigmoid_resultUSA::executive_departments_norm,
        "executive_departments_sigmoid", &government_sigmoid_resultUSA::executive_departments_sigmoid,
        "house_seats", &government_sigmoid_resultUSA::house_seats,
        "house_seats_min", &government_sigmoid_resultUSA::house_seats_min,
        "house_seats_max", &government_sigmoid_resultUSA::house_seats_max,
        "house_seats_norm", &government_sigmoid_resultUSA::house_seats_norm,
        "house_seats_sigmoid", &government_sigmoid_resultUSA::house_seats_sigmoid,
        "senate_seats", &government_sigmoid_resultUSA::senate_seats,
        "senate_seats_min", &government_sigmoid_resultUSA::senate_seats_min,
        "senate_seats_max", &government_sigmoid_resultUSA::senate_seats_max,
        "senate_seats_norm", &government_sigmoid_resultUSA::senate_seats_norm,
        "senate_seats_sigmoid", &government_sigmoid_resultUSA::senate_seats_sigmoid,
        "supreme_court_justices", &government_sigmoid_resultUSA::supreme_court_justices,
        "supreme_court_justices_min", &government_sigmoid_resultUSA::supreme_court_justices_min,
        "supreme_court_justices_max", &government_sigmoid_resultUSA::supreme_court_justices_max,
        "supreme_court_justices_norm", &government_sigmoid_resultUSA::supreme_court_justices_norm,
        "supreme_court_justices_sigmoid", &government_sigmoid_resultUSA::supreme_court_justices_sigmoid
    );

    lua.new_usertype<demography_HighBest_sigmoid_resultUSA>("demography_HighBest_sigmoid_resultUSA",
        "population", &demography_HighBest_sigmoid_resultUSA::population,
        "population_min", &demography_HighBest_sigmoid_resultUSA::population_min,
        "population_max", &demography_HighBest_sigmoid_resultUSA::population_max,
        "population_norm", &demography_HighBest_sigmoid_resultUSA::population_norm,
        "population_sigmoid", &demography_HighBest_sigmoid_resultUSA::population_sigmoid,
        "population_growth_rate", &demography_HighBest_sigmoid_resultUSA::population_growth_rate,
        "population_growth_rate_min", &demography_HighBest_sigmoid_resultUSA::population_growth_rate_min,
        "population_growth_rate_max", &demography_HighBest_sigmoid_resultUSA::population_growth_rate_max,
        "population_growth_rate_norm", &demography_HighBest_sigmoid_resultUSA::population_growth_rate_norm,
        "population_growth_rate_sigmoid", &demography_HighBest_sigmoid_resultUSA::population_growth_rate_sigmoid,
        "population_density", &demography_HighBest_sigmoid_resultUSA::population_density,
        "population_density_min", &demography_HighBest_sigmoid_resultUSA::population_density_min,
        "population_density_max", &demography_HighBest_sigmoid_resultUSA::population_density_max,
        "population_density_norm", &demography_HighBest_sigmoid_resultUSA::population_density_norm,
        "population_density_sigmoid", &demography_HighBest_sigmoid_resultUSA::population_density_sigmoid,
        "births", &demography_HighBest_sigmoid_resultUSA::births,
        "births_min", &demography_HighBest_sigmoid_resultUSA::births_min,
        "births_max", &demography_HighBest_sigmoid_resultUSA::births_max,
        "births_norm", &demography_HighBest_sigmoid_resultUSA::births_norm,
        "births_sigmoid", &demography_HighBest_sigmoid_resultUSA::births_sigmoid,
        "birth_rate", &demography_HighBest_sigmoid_resultUSA::birth_rate,
        "birth_rate_min", &demography_HighBest_sigmoid_resultUSA::birth_rate_min,
        "birth_rate_max", &demography_HighBest_sigmoid_resultUSA::birth_rate_max,
        "birth_rate_norm", &demography_HighBest_sigmoid_resultUSA::birth_rate_norm,
        "birth_rate_sigmoid", &demography_HighBest_sigmoid_resultUSA::birth_rate_sigmoid,
        "fertility_rate", &demography_HighBest_sigmoid_resultUSA::fertility_rate,
        "fertility_rate_min", &demography_HighBest_sigmoid_resultUSA::fertility_rate_min,
        "fertility_rate_max", &demography_HighBest_sigmoid_resultUSA::fertility_rate_max,
        "fertility_rate_norm", &demography_HighBest_sigmoid_resultUSA::fertility_rate_norm,
        "fertility_rate_sigmoid", &demography_HighBest_sigmoid_resultUSA::fertility_rate_sigmoid,
        "life_expectancy", &demography_HighBest_sigmoid_resultUSA::life_expectancy,
        "life_expectancy_min", &demography_HighBest_sigmoid_resultUSA::life_expectancy_min,
        "life_expectancy_max", &demography_HighBest_sigmoid_resultUSA::life_expectancy_max,
        "life_expectancy_norm", &demography_HighBest_sigmoid_resultUSA::life_expectancy_norm,
        "life_expectancy_sigmoid", &demography_HighBest_sigmoid_resultUSA::life_expectancy_sigmoid,
        "life_expectancy_male", &demography_HighBest_sigmoid_resultUSA::life_expectancy_male,
        "life_expectancy_male_min", &demography_HighBest_sigmoid_resultUSA::life_expectancy_male_min,
        "life_expectancy_male_max", &demography_HighBest_sigmoid_resultUSA::life_expectancy_male_max,
        "life_expectancy_male_norm", &demography_HighBest_sigmoid_resultUSA::life_expectancy_male_norm,
        "life_expectancy_male_sigmoid", &demography_HighBest_sigmoid_resultUSA::life_expectancy_male_sigmoid,
        "life_expectancy_female", &demography_HighBest_sigmoid_resultUSA::life_expectancy_female,
        "life_expectancy_female_min", &demography_HighBest_sigmoid_resultUSA::life_expectancy_female_min,
        "life_expectancy_female_max", &demography_HighBest_sigmoid_resultUSA::life_expectancy_female_max,
        "life_expectancy_female_norm", &demography_HighBest_sigmoid_resultUSA::life_expectancy_female_norm,
        "life_expectancy_female_sigmoid", &demography_HighBest_sigmoid_resultUSA::life_expectancy_female_sigmoid,
        "urban_population_pct", &demography_HighBest_sigmoid_resultUSA::urban_population_pct,
        "urban_population_pct_min", &demography_HighBest_sigmoid_resultUSA::urban_population_pct_min,
        "urban_population_pct_max", &demography_HighBest_sigmoid_resultUSA::urban_population_pct_max,
        "urban_population_pct_norm", &demography_HighBest_sigmoid_resultUSA::urban_population_pct_norm,
        "urban_population_pct_sigmoid", &demography_HighBest_sigmoid_resultUSA::urban_population_pct_sigmoid,
        "male_pct", &demography_HighBest_sigmoid_resultUSA::male_pct,
        "male_pct_min", &demography_HighBest_sigmoid_resultUSA::male_pct_min,
        "male_pct_max", &demography_HighBest_sigmoid_resultUSA::male_pct_max,
        "male_pct_norm", &demography_HighBest_sigmoid_resultUSA::male_pct_norm,
        "male_pct_sigmoid", &demography_HighBest_sigmoid_resultUSA::male_pct_sigmoid,
        "female_pct", &demography_HighBest_sigmoid_resultUSA::female_pct,
        "female_pct_min", &demography_HighBest_sigmoid_resultUSA::female_pct_min,
        "female_pct_max", &demography_HighBest_sigmoid_resultUSA::female_pct_max,
        "female_pct_norm", &demography_HighBest_sigmoid_resultUSA::female_pct_norm,
        "female_pct_sigmoid", &demography_HighBest_sigmoid_resultUSA::female_pct_sigmoid,
        "age_under_18_pct", &demography_HighBest_sigmoid_resultUSA::age_under_18_pct,
        "age_under_18_pct_min", &demography_HighBest_sigmoid_resultUSA::age_under_18_pct_min,
        "age_under_18_pct_max", &demography_HighBest_sigmoid_resultUSA::age_under_18_pct_max,
        "age_under_18_pct_norm", &demography_HighBest_sigmoid_resultUSA::age_under_18_pct_norm,
        "age_under_18_pct_sigmoid", &demography_HighBest_sigmoid_resultUSA::age_under_18_pct_sigmoid,
        "age_18_64_pct", &demography_HighBest_sigmoid_resultUSA::age_18_64_pct,
        "age_18_64_pct_min", &demography_HighBest_sigmoid_resultUSA::age_18_64_pct_min,
        "age_18_64_pct_max", &demography_HighBest_sigmoid_resultUSA::age_18_64_pct_max,
        "age_18_64_pct_norm", &demography_HighBest_sigmoid_resultUSA::age_18_64_pct_norm,
        "age_18_64_pct_sigmoid", &demography_HighBest_sigmoid_resultUSA::age_18_64_pct_sigmoid,
        "age_65_plus_pct", &demography_HighBest_sigmoid_resultUSA::age_65_plus_pct,
        "age_65_plus_pct_min", &demography_HighBest_sigmoid_resultUSA::age_65_plus_pct_min,
        "age_65_plus_pct_max", &demography_HighBest_sigmoid_resultUSA::age_65_plus_pct_max,
        "age_65_plus_pct_norm", &demography_HighBest_sigmoid_resultUSA::age_65_plus_pct_norm,
        "age_65_plus_pct_sigmoid", &demography_HighBest_sigmoid_resultUSA::age_65_plus_pct_sigmoid,
        "net_migration", &demography_HighBest_sigmoid_resultUSA::net_migration,
        "net_migration_min", &demography_HighBest_sigmoid_resultUSA::net_migration_min,
        "net_migration_max", &demography_HighBest_sigmoid_resultUSA::net_migration_max,
        "net_migration_norm", &demography_HighBest_sigmoid_resultUSA::net_migration_norm,
        "net_migration_sigmoid", &demography_HighBest_sigmoid_resultUSA::net_migration_sigmoid,
        "households", &demography_HighBest_sigmoid_resultUSA::households,
        "households_min", &demography_HighBest_sigmoid_resultUSA::households_min,
        "households_max", &demography_HighBest_sigmoid_resultUSA::households_max,
        "households_norm", &demography_HighBest_sigmoid_resultUSA::households_norm,
        "households_sigmoid", &demography_HighBest_sigmoid_resultUSA::households_sigmoid,
        "homeownership_rate", &demography_HighBest_sigmoid_resultUSA::homeownership_rate,
        "homeownership_rate_min", &demography_HighBest_sigmoid_resultUSA::homeownership_rate_min,
        "homeownership_rate_max", &demography_HighBest_sigmoid_resultUSA::homeownership_rate_max,
        "homeownership_rate_norm", &demography_HighBest_sigmoid_resultUSA::homeownership_rate_norm,
        "homeownership_rate_sigmoid", &demography_HighBest_sigmoid_resultUSA::homeownership_rate_sigmoid
    );

    lua.new_usertype<demography_LowBest_sigmoid_resultUSA>("demography_LowBest_sigmoid_resultUSA",
        "deaths", &demography_LowBest_sigmoid_resultUSA::deaths,
        "deaths_min", &demography_LowBest_sigmoid_resultUSA::deaths_min,
        "deaths_max", &demography_LowBest_sigmoid_resultUSA::deaths_max,
        "deaths_norm", &demography_LowBest_sigmoid_resultUSA::deaths_norm,
        "deaths_sigmoid", &demography_LowBest_sigmoid_resultUSA::deaths_sigmoid,
        "death_rate", &demography_LowBest_sigmoid_resultUSA::death_rate,
        "death_rate_min", &demography_LowBest_sigmoid_resultUSA::death_rate_min,
        "death_rate_max", &demography_LowBest_sigmoid_resultUSA::death_rate_max,
        "death_rate_norm", &demography_LowBest_sigmoid_resultUSA::death_rate_norm,
        "death_rate_sigmoid", &demography_LowBest_sigmoid_resultUSA::death_rate_sigmoid,
        "median_age", &demography_LowBest_sigmoid_resultUSA::median_age,
        "median_age_min", &demography_LowBest_sigmoid_resultUSA::median_age_min,
        "median_age_max", &demography_LowBest_sigmoid_resultUSA::median_age_max,
        "median_age_norm", &demography_LowBest_sigmoid_resultUSA::median_age_norm,
        "median_age_sigmoid", &demography_LowBest_sigmoid_resultUSA::median_age_sigmoid,
        "infant_mortality", &demography_LowBest_sigmoid_resultUSA::infant_mortality,
        "infant_mortality_min", &demography_LowBest_sigmoid_resultUSA::infant_mortality_min,
        "infant_mortality_max", &demography_LowBest_sigmoid_resultUSA::infant_mortality_max,
        "infant_mortality_norm", &demography_LowBest_sigmoid_resultUSA::infant_mortality_norm,
        "infant_mortality_sigmoid", &demography_LowBest_sigmoid_resultUSA::infant_mortality_sigmoid
    );

    lua.new_usertype<economy_HighBest_sigmoid_resultUSA>("economy_HighBest_sigmoid_resultUSA",
        "gdp_current", &economy_HighBest_sigmoid_resultUSA::gdp_current,
        "gdp_current_min", &economy_HighBest_sigmoid_resultUSA::gdp_current_min,
        "gdp_current_max", &economy_HighBest_sigmoid_resultUSA::gdp_current_max,
        "gdp_current_norm", &economy_HighBest_sigmoid_resultUSA::gdp_current_norm,
        "gdp_current_sigmoid", &economy_HighBest_sigmoid_resultUSA::gdp_current_sigmoid,
        "gdp_real_growth", &economy_HighBest_sigmoid_resultUSA::gdp_real_growth,
        "gdp_real_growth_min", &economy_HighBest_sigmoid_resultUSA::gdp_real_growth_min,
        "gdp_real_growth_max", &economy_HighBest_sigmoid_resultUSA::gdp_real_growth_max,
        "gdp_real_growth_norm", &economy_HighBest_sigmoid_resultUSA::gdp_real_growth_norm,
        "gdp_real_growth_sigmoid", &economy_HighBest_sigmoid_resultUSA::gdp_real_growth_sigmoid,
        "gdp_per_capita", &economy_HighBest_sigmoid_resultUSA::gdp_per_capita,
        "gdp_per_capita_min", &economy_HighBest_sigmoid_resultUSA::gdp_per_capita_min,
        "gdp_per_capita_max", &economy_HighBest_sigmoid_resultUSA::gdp_per_capita_max,
        "gdp_per_capita_norm", &economy_HighBest_sigmoid_resultUSA::gdp_per_capita_norm,
        "gdp_per_capita_sigmoid", &economy_HighBest_sigmoid_resultUSA::gdp_per_capita_sigmoid,
        "labor_force", &economy_HighBest_sigmoid_resultUSA::labor_force,
        "labor_force_min", &economy_HighBest_sigmoid_resultUSA::labor_force_min,
        "labor_force_max", &economy_HighBest_sigmoid_resultUSA::labor_force_max,
        "labor_force_norm", &economy_HighBest_sigmoid_resultUSA::labor_force_norm,
        "labor_force_sigmoid", &economy_HighBest_sigmoid_resultUSA::labor_force_sigmoid,
        "labor_force_participation", &economy_HighBest_sigmoid_resultUSA::labor_force_participation,
        "labor_force_participation_min", &economy_HighBest_sigmoid_resultUSA::labor_force_participation_min,
        "labor_force_participation_max", &economy_HighBest_sigmoid_resultUSA::labor_force_participation_max,
        "labor_force_participation_norm", &economy_HighBest_sigmoid_resultUSA::labor_force_participation_norm,
        "labor_force_participation_sigmoid", &economy_HighBest_sigmoid_resultUSA::labor_force_participation_sigmoid,
        "employed", &economy_HighBest_sigmoid_resultUSA::employed,
        "employed_min", &economy_HighBest_sigmoid_resultUSA::employed_min,
        "employed_max", &economy_HighBest_sigmoid_resultUSA::employed_max,
        "employed_norm", &economy_HighBest_sigmoid_resultUSA::employed_norm,
        "employed_sigmoid", &economy_HighBest_sigmoid_resultUSA::employed_sigmoid,
        "median_household_income", &economy_HighBest_sigmoid_resultUSA::median_household_income,
        "median_household_income_min", &economy_HighBest_sigmoid_resultUSA::median_household_income_min,
        "median_household_income_max", &economy_HighBest_sigmoid_resultUSA::median_household_income_max,
        "median_household_income_norm", &economy_HighBest_sigmoid_resultUSA::median_household_income_norm,
        "median_household_income_sigmoid", &economy_HighBest_sigmoid_resultUSA::median_household_income_sigmoid,
        "federal_revenue", &economy_HighBest_sigmoid_resultUSA::federal_revenue,
        "federal_revenue_min", &economy_HighBest_sigmoid_resultUSA::federal_revenue_min,
        "federal_revenue_max", &economy_HighBest_sigmoid_resultUSA::federal_revenue_max,
        "federal_revenue_norm", &economy_HighBest_sigmoid_resultUSA::federal_revenue_norm,
        "federal_revenue_sigmoid", &economy_HighBest_sigmoid_resultUSA::federal_revenue_sigmoid,
        "foreign_exchange_reserves", &economy_HighBest_sigmoid_resultUSA::foreign_exchange_reserves,
        "foreign_exchange_reserves_min", &economy_HighBest_sigmoid_resultUSA::foreign_exchange_reserves_min,
        "foreign_exchange_reserves_max", &economy_HighBest_sigmoid_resultUSA::foreign_exchange_reserves_max,
        "foreign_exchange_reserves_norm", &economy_HighBest_sigmoid_resultUSA::foreign_exchange_reserves_norm,
        "foreign_exchange_reserves_sigmoid", &economy_HighBest_sigmoid_resultUSA::foreign_exchange_reserves_sigmoid,
        "fdi_inflow", &economy_HighBest_sigmoid_resultUSA::fdi_inflow,
        "fdi_inflow_min", &economy_HighBest_sigmoid_resultUSA::fdi_inflow_min,
        "fdi_inflow_max", &economy_HighBest_sigmoid_resultUSA::fdi_inflow_max,
        "fdi_inflow_norm", &economy_HighBest_sigmoid_resultUSA::fdi_inflow_norm,
        "fdi_inflow_sigmoid", &economy_HighBest_sigmoid_resultUSA::fdi_inflow_sigmoid,
        "services_share", &economy_HighBest_sigmoid_resultUSA::services_share,
        "services_share_min", &economy_HighBest_sigmoid_resultUSA::services_share_min,
        "services_share_max", &economy_HighBest_sigmoid_resultUSA::services_share_max,
        "services_share_norm", &economy_HighBest_sigmoid_resultUSA::services_share_norm,
        "services_share_sigmoid", &economy_HighBest_sigmoid_resultUSA::services_share_sigmoid,
        "industry_share", &economy_HighBest_sigmoid_resultUSA::industry_share,
        "industry_share_min", &economy_HighBest_sigmoid_resultUSA::industry_share_min,
        "industry_share_max", &economy_HighBest_sigmoid_resultUSA::industry_share_max,
        "industry_share_norm", &economy_HighBest_sigmoid_resultUSA::industry_share_norm,
        "industry_share_sigmoid", &economy_HighBest_sigmoid_resultUSA::industry_share_sigmoid,
        "agriculture_share", &economy_HighBest_sigmoid_resultUSA::agriculture_share,
        "agriculture_share_min", &economy_HighBest_sigmoid_resultUSA::agriculture_share_min,
        "agriculture_share_max", &economy_HighBest_sigmoid_resultUSA::agriculture_share_max,
        "agriculture_share_norm", &economy_HighBest_sigmoid_resultUSA::agriculture_share_norm,
        "agriculture_share_sigmoid", &economy_HighBest_sigmoid_resultUSA::agriculture_share_sigmoid,
        "manufacturing_share", &economy_HighBest_sigmoid_resultUSA::manufacturing_share,
        "manufacturing_share_min", &economy_HighBest_sigmoid_resultUSA::manufacturing_share_min,
        "manufacturing_share_max", &economy_HighBest_sigmoid_resultUSA::manufacturing_share_max,
        "manufacturing_share_norm", &economy_HighBest_sigmoid_resultUSA::manufacturing_share_norm,
        "manufacturing_share_sigmoid", &economy_HighBest_sigmoid_resultUSA::manufacturing_share_sigmoid,
        "minimum_wage_federal", &economy_HighBest_sigmoid_resultUSA::minimum_wage_federal,
        "minimum_wage_federal_min", &economy_HighBest_sigmoid_resultUSA::minimum_wage_federal_min,
        "minimum_wage_federal_max", &economy_HighBest_sigmoid_resultUSA::minimum_wage_federal_max,
        "minimum_wage_federal_norm", &economy_HighBest_sigmoid_resultUSA::minimum_wage_federal_norm,
        "minimum_wage_federal_sigmoid", &economy_HighBest_sigmoid_resultUSA::minimum_wage_federal_sigmoid,
        "union_membership_rate", &economy_HighBest_sigmoid_resultUSA::union_membership_rate,
        "union_membership_rate_min", &economy_HighBest_sigmoid_resultUSA::union_membership_rate_min,
        "union_membership_rate_max", &economy_HighBest_sigmoid_resultUSA::union_membership_rate_max,
        "union_membership_rate_norm", &economy_HighBest_sigmoid_resultUSA::union_membership_rate_norm,
        "union_membership_rate_sigmoid", &economy_HighBest_sigmoid_resultUSA::union_membership_rate_sigmoid
    );

    lua.new_usertype<economy_LowBest_sigmoid_resultUSA>("economy_LowBest_sigmoid_resultUSA",
        "inflation_rate", &economy_LowBest_sigmoid_resultUSA::inflation_rate,
        "inflation_rate_min", &economy_LowBest_sigmoid_resultUSA::inflation_rate_min,
        "inflation_rate_max", &economy_LowBest_sigmoid_resultUSA::inflation_rate_max,
        "inflation_rate_norm", &economy_LowBest_sigmoid_resultUSA::inflation_rate_norm,
        "inflation_rate_sigmoid", &economy_LowBest_sigmoid_resultUSA::inflation_rate_sigmoid,
        "unemployment_rate", &economy_LowBest_sigmoid_resultUSA::unemployment_rate,
        "unemployment_rate_min", &economy_LowBest_sigmoid_resultUSA::unemployment_rate_min,
        "unemployment_rate_max", &economy_LowBest_sigmoid_resultUSA::unemployment_rate_max,
        "unemployment_rate_norm", &economy_LowBest_sigmoid_resultUSA::unemployment_rate_norm,
        "unemployment_rate_sigmoid", &economy_LowBest_sigmoid_resultUSA::unemployment_rate_sigmoid,
        "unemployed", &economy_LowBest_sigmoid_resultUSA::unemployed,
        "unemployed_min", &economy_LowBest_sigmoid_resultUSA::unemployed_min,
        "unemployed_max", &economy_LowBest_sigmoid_resultUSA::unemployed_max,
        "unemployed_norm", &economy_LowBest_sigmoid_resultUSA::unemployed_norm,
        "unemployed_sigmoid", &economy_LowBest_sigmoid_resultUSA::unemployed_sigmoid,
        "poverty_rate", &economy_LowBest_sigmoid_resultUSA::poverty_rate,
        "poverty_rate_min", &economy_LowBest_sigmoid_resultUSA::poverty_rate_min,
        "poverty_rate_max", &economy_LowBest_sigmoid_resultUSA::poverty_rate_max,
        "poverty_rate_norm", &economy_LowBest_sigmoid_resultUSA::poverty_rate_norm,
        "poverty_rate_sigmoid", &economy_LowBest_sigmoid_resultUSA::poverty_rate_sigmoid,
        "gini_index", &economy_LowBest_sigmoid_resultUSA::gini_index,
        "gini_index_min", &economy_LowBest_sigmoid_resultUSA::gini_index_min,
        "gini_index_max", &economy_LowBest_sigmoid_resultUSA::gini_index_max,
        "gini_index_norm", &economy_LowBest_sigmoid_resultUSA::gini_index_norm,
        "gini_index_sigmoid", &economy_LowBest_sigmoid_resultUSA::gini_index_sigmoid,
        "federal_spending", &economy_LowBest_sigmoid_resultUSA::federal_spending,
        "federal_spending_min", &economy_LowBest_sigmoid_resultUSA::federal_spending_min,
        "federal_spending_max", &economy_LowBest_sigmoid_resultUSA::federal_spending_max,
        "federal_spending_norm", &economy_LowBest_sigmoid_resultUSA::federal_spending_norm,
        "federal_spending_sigmoid", &economy_LowBest_sigmoid_resultUSA::federal_spending_sigmoid,
        "budget_balance", &economy_LowBest_sigmoid_resultUSA::budget_balance,
        "budget_balance_min", &economy_LowBest_sigmoid_resultUSA::budget_balance_min,
        "budget_balance_max", &economy_LowBest_sigmoid_resultUSA::budget_balance_max,
        "budget_balance_norm", &economy_LowBest_sigmoid_resultUSA::budget_balance_norm,
        "budget_balance_sigmoid", &economy_LowBest_sigmoid_resultUSA::budget_balance_sigmoid,
        "public_debt", &economy_LowBest_sigmoid_resultUSA::public_debt,
        "public_debt_min", &economy_LowBest_sigmoid_resultUSA::public_debt_min,
        "public_debt_max", &economy_LowBest_sigmoid_resultUSA::public_debt_max,
        "public_debt_norm", &economy_LowBest_sigmoid_resultUSA::public_debt_norm,
        "public_debt_sigmoid", &economy_LowBest_sigmoid_resultUSA::public_debt_sigmoid,
        "household_debt", &economy_LowBest_sigmoid_resultUSA::household_debt,
        "household_debt_min", &economy_LowBest_sigmoid_resultUSA::household_debt_min,
        "household_debt_max", &economy_LowBest_sigmoid_resultUSA::household_debt_max,
        "household_debt_norm", &economy_LowBest_sigmoid_resultUSA::household_debt_norm,
        "household_debt_sigmoid", &economy_LowBest_sigmoid_resultUSA::household_debt_sigmoid,
        "exports", &economy_LowBest_sigmoid_resultUSA::exports,
        "exports_min", &economy_LowBest_sigmoid_resultUSA::exports_min,
        "exports_max", &economy_LowBest_sigmoid_resultUSA::exports_max,
        "exports_norm", &economy_LowBest_sigmoid_resultUSA::exports_norm,
        "exports_sigmoid", &economy_LowBest_sigmoid_resultUSA::exports_sigmoid,
        "imports", &economy_LowBest_sigmoid_resultUSA::imports,
        "imports_min", &economy_LowBest_sigmoid_resultUSA::imports_min,
        "imports_max", &economy_LowBest_sigmoid_resultUSA::imports_max,
        "imports_norm", &economy_LowBest_sigmoid_resultUSA::imports_norm,
        "imports_sigmoid", &economy_LowBest_sigmoid_resultUSA::imports_sigmoid,
        "trade_balance", &economy_LowBest_sigmoid_resultUSA::trade_balance,
        "trade_balance_min", &economy_LowBest_sigmoid_resultUSA::trade_balance_min,
        "trade_balance_max", &economy_LowBest_sigmoid_resultUSA::trade_balance_max,
        "trade_balance_norm", &economy_LowBest_sigmoid_resultUSA::trade_balance_norm,
        "trade_balance_sigmoid", &economy_LowBest_sigmoid_resultUSA::trade_balance_sigmoid,
        "corporate_tax_rate", &economy_LowBest_sigmoid_resultUSA::corporate_tax_rate,
        "corporate_tax_rate_min", &economy_LowBest_sigmoid_resultUSA::corporate_tax_rate_min,
        "corporate_tax_rate_max", &economy_LowBest_sigmoid_resultUSA::corporate_tax_rate_max,
        "corporate_tax_rate_norm", &economy_LowBest_sigmoid_resultUSA::corporate_tax_rate_norm,
        "corporate_tax_rate_sigmoid", &economy_LowBest_sigmoid_resultUSA::corporate_tax_rate_sigmoid,
        "personal_tax_top_rate", &economy_LowBest_sigmoid_resultUSA::personal_tax_top_rate,
        "personal_tax_top_rate_min", &economy_LowBest_sigmoid_resultUSA::personal_tax_top_rate_min,
        "personal_tax_top_rate_max", &economy_LowBest_sigmoid_resultUSA::personal_tax_top_rate_max,
        "personal_tax_top_rate_norm", &economy_LowBest_sigmoid_resultUSA::personal_tax_top_rate_norm,
        "personal_tax_top_rate_sigmoid", &economy_LowBest_sigmoid_resultUSA::personal_tax_top_rate_sigmoid,
        "policy_rate", &economy_LowBest_sigmoid_resultUSA::policy_rate,
        "policy_rate_min", &economy_LowBest_sigmoid_resultUSA::policy_rate_min,
        "policy_rate_max", &economy_LowBest_sigmoid_resultUSA::policy_rate_max,
        "policy_rate_norm", &economy_LowBest_sigmoid_resultUSA::policy_rate_norm,
        "policy_rate_sigmoid", &economy_LowBest_sigmoid_resultUSA::policy_rate_sigmoid
    );

    lua.new_usertype<government_HighBest_sigmoid_resultUSA>("government_HighBest_sigmoid_resultUSA",
        "approval_rating", &government_HighBest_sigmoid_resultUSA::approval_rating,
        "approval_rating_min", &government_HighBest_sigmoid_resultUSA::approval_rating_min,
        "approval_rating_max", &government_HighBest_sigmoid_resultUSA::approval_rating_max,
        "approval_rating_norm", &government_HighBest_sigmoid_resultUSA::approval_rating_norm,
        "approval_rating_sigmoid", &government_HighBest_sigmoid_resultUSA::approval_rating_sigmoid
    );

    lua.new_usertype<government_LowBest_sigmoid_resultUSA>("government_LowBest_sigmoid_resultUSA",
        "federal_employees", &government_LowBest_sigmoid_resultUSA::federal_employees,
        "federal_employees_min", &government_LowBest_sigmoid_resultUSA::federal_employees_min,
        "federal_employees_max", &government_LowBest_sigmoid_resultUSA::federal_employees_max,
        "federal_employees_norm", &government_LowBest_sigmoid_resultUSA::federal_employees_norm,
        "federal_employees_sigmoid", &government_LowBest_sigmoid_resultUSA::federal_employees_sigmoid
    );

    lua.new_usertype<military_HighBest_sigmoid_resultUSA>("military_HighBest_sigmoid_resultUSA",
        "defense_budget", &military_HighBest_sigmoid_resultUSA::defense_budget,
        "defense_budget_min", &military_HighBest_sigmoid_resultUSA::defense_budget_min,
        "defense_budget_max", &military_HighBest_sigmoid_resultUSA::defense_budget_max,
        "defense_budget_norm", &military_HighBest_sigmoid_resultUSA::defense_budget_norm,
        "defense_budget_sigmoid", &military_HighBest_sigmoid_resultUSA::defense_budget_sigmoid,
        "active_personnel", &military_HighBest_sigmoid_resultUSA::active_personnel,
        "active_personnel_min", &military_HighBest_sigmoid_resultUSA::active_personnel_min,
        "active_personnel_max", &military_HighBest_sigmoid_resultUSA::active_personnel_max,
        "active_personnel_norm", &military_HighBest_sigmoid_resultUSA::active_personnel_norm,
        "active_personnel_sigmoid", &military_HighBest_sigmoid_resultUSA::active_personnel_sigmoid,
        "reserve_personnel", &military_HighBest_sigmoid_resultUSA::reserve_personnel,
        "reserve_personnel_min", &military_HighBest_sigmoid_resultUSA::reserve_personnel_min,
        "reserve_personnel_max", &military_HighBest_sigmoid_resultUSA::reserve_personnel_max,
        "reserve_personnel_norm", &military_HighBest_sigmoid_resultUSA::reserve_personnel_norm,
        "reserve_personnel_sigmoid", &military_HighBest_sigmoid_resultUSA::reserve_personnel_sigmoid,
        "national_guard_personnel", &military_HighBest_sigmoid_resultUSA::national_guard_personnel,
        "national_guard_personnel_min", &military_HighBest_sigmoid_resultUSA::national_guard_personnel_min,
        "national_guard_personnel_max", &military_HighBest_sigmoid_resultUSA::national_guard_personnel_max,
        "national_guard_personnel_norm", &military_HighBest_sigmoid_resultUSA::national_guard_personnel_norm,
        "national_guard_personnel_sigmoid", &military_HighBest_sigmoid_resultUSA::national_guard_personnel_sigmoid,
        "army_personnel", &military_HighBest_sigmoid_resultUSA::army_personnel,
        "army_personnel_min", &military_HighBest_sigmoid_resultUSA::army_personnel_min,
        "army_personnel_max", &military_HighBest_sigmoid_resultUSA::army_personnel_max,
        "army_personnel_norm", &military_HighBest_sigmoid_resultUSA::army_personnel_norm,
        "army_personnel_sigmoid", &military_HighBest_sigmoid_resultUSA::army_personnel_sigmoid,
        "navy_personnel", &military_HighBest_sigmoid_resultUSA::navy_personnel,
        "navy_personnel_min", &military_HighBest_sigmoid_resultUSA::navy_personnel_min,
        "navy_personnel_max", &military_HighBest_sigmoid_resultUSA::navy_personnel_max,
        "navy_personnel_norm", &military_HighBest_sigmoid_resultUSA::navy_personnel_norm,
        "navy_personnel_sigmoid", &military_HighBest_sigmoid_resultUSA::navy_personnel_sigmoid,
        "air_force_personnel", &military_HighBest_sigmoid_resultUSA::air_force_personnel,
        "air_force_personnel_min", &military_HighBest_sigmoid_resultUSA::air_force_personnel_min,
        "air_force_personnel_max", &military_HighBest_sigmoid_resultUSA::air_force_personnel_max,
        "air_force_personnel_norm", &military_HighBest_sigmoid_resultUSA::air_force_personnel_norm,
        "air_force_personnel_sigmoid", &military_HighBest_sigmoid_resultUSA::air_force_personnel_sigmoid,
        "marine_personnel", &military_HighBest_sigmoid_resultUSA::marine_personnel,
        "marine_personnel_min", &military_HighBest_sigmoid_resultUSA::marine_personnel_min,
        "marine_personnel_max", &military_HighBest_sigmoid_resultUSA::marine_personnel_max,
        "marine_personnel_norm", &military_HighBest_sigmoid_resultUSA::marine_personnel_norm,
        "marine_personnel_sigmoid", &military_HighBest_sigmoid_resultUSA::marine_personnel_sigmoid,
        "space_force_personnel", &military_HighBest_sigmoid_resultUSA::space_force_personnel,
        "space_force_personnel_min", &military_HighBest_sigmoid_resultUSA::space_force_personnel_min,
        "space_force_personnel_max", &military_HighBest_sigmoid_resultUSA::space_force_personnel_max,
        "space_force_personnel_norm", &military_HighBest_sigmoid_resultUSA::space_force_personnel_norm,
        "space_force_personnel_sigmoid", &military_HighBest_sigmoid_resultUSA::space_force_personnel_sigmoid,
        "nuclear_warheads", &military_HighBest_sigmoid_resultUSA::nuclear_warheads,
        "nuclear_warheads_min", &military_HighBest_sigmoid_resultUSA::nuclear_warheads_min,
        "nuclear_warheads_max", &military_HighBest_sigmoid_resultUSA::nuclear_warheads_max,
        "nuclear_warheads_norm", &military_HighBest_sigmoid_resultUSA::nuclear_warheads_norm,
        "nuclear_warheads_sigmoid", &military_HighBest_sigmoid_resultUSA::nuclear_warheads_sigmoid,
        "carriers", &military_HighBest_sigmoid_resultUSA::carriers,
        "carriers_min", &military_HighBest_sigmoid_resultUSA::carriers_min,
        "carriers_max", &military_HighBest_sigmoid_resultUSA::carriers_max,
        "carriers_norm", &military_HighBest_sigmoid_resultUSA::carriers_norm,
        "carriers_sigmoid", &military_HighBest_sigmoid_resultUSA::carriers_sigmoid,
        "destroyers", &military_HighBest_sigmoid_resultUSA::destroyers,
        "destroyers_min", &military_HighBest_sigmoid_resultUSA::destroyers_min,
        "destroyers_max", &military_HighBest_sigmoid_resultUSA::destroyers_max,
        "destroyers_norm", &military_HighBest_sigmoid_resultUSA::destroyers_norm,
        "destroyers_sigmoid", &military_HighBest_sigmoid_resultUSA::destroyers_sigmoid,
        "submarines", &military_HighBest_sigmoid_resultUSA::submarines,
        "submarines_min", &military_HighBest_sigmoid_resultUSA::submarines_min,
        "submarines_max", &military_HighBest_sigmoid_resultUSA::submarines_max,
        "submarines_norm", &military_HighBest_sigmoid_resultUSA::submarines_norm,
        "submarines_sigmoid", &military_HighBest_sigmoid_resultUSA::submarines_sigmoid,
        "tanks", &military_HighBest_sigmoid_resultUSA::tanks,
        "tanks_min", &military_HighBest_sigmoid_resultUSA::tanks_min,
        "tanks_max", &military_HighBest_sigmoid_resultUSA::tanks_max,
        "tanks_norm", &military_HighBest_sigmoid_resultUSA::tanks_norm,
        "tanks_sigmoid", &military_HighBest_sigmoid_resultUSA::tanks_sigmoid,
        "armored_vehicles", &military_HighBest_sigmoid_resultUSA::armored_vehicles,
        "armored_vehicles_min", &military_HighBest_sigmoid_resultUSA::armored_vehicles_min,
        "armored_vehicles_max", &military_HighBest_sigmoid_resultUSA::armored_vehicles_max,
        "armored_vehicles_norm", &military_HighBest_sigmoid_resultUSA::armored_vehicles_norm,
        "armored_vehicles_sigmoid", &military_HighBest_sigmoid_resultUSA::armored_vehicles_sigmoid,
        "fighter_aircraft", &military_HighBest_sigmoid_resultUSA::fighter_aircraft,
        "fighter_aircraft_min", &military_HighBest_sigmoid_resultUSA::fighter_aircraft_min,
        "fighter_aircraft_max", &military_HighBest_sigmoid_resultUSA::fighter_aircraft_max,
        "fighter_aircraft_norm", &military_HighBest_sigmoid_resultUSA::fighter_aircraft_norm,
        "fighter_aircraft_sigmoid", &military_HighBest_sigmoid_resultUSA::fighter_aircraft_sigmoid,
        "bombers", &military_HighBest_sigmoid_resultUSA::bombers,
        "bombers_min", &military_HighBest_sigmoid_resultUSA::bombers_min,
        "bombers_max", &military_HighBest_sigmoid_resultUSA::bombers_max,
        "bombers_norm", &military_HighBest_sigmoid_resultUSA::bombers_norm,
        "bombers_sigmoid", &military_HighBest_sigmoid_resultUSA::bombers_sigmoid,
        "attack_helicopters", &military_HighBest_sigmoid_resultUSA::attack_helicopters,
        "attack_helicopters_min", &military_HighBest_sigmoid_resultUSA::attack_helicopters_min,
        "attack_helicopters_max", &military_HighBest_sigmoid_resultUSA::attack_helicopters_max,
        "attack_helicopters_norm", &military_HighBest_sigmoid_resultUSA::attack_helicopters_norm,
        "attack_helicopters_sigmoid", &military_HighBest_sigmoid_resultUSA::attack_helicopters_sigmoid,
        "transport_aircraft", &military_HighBest_sigmoid_resultUSA::transport_aircraft,
        "transport_aircraft_min", &military_HighBest_sigmoid_resultUSA::transport_aircraft_min,
        "transport_aircraft_max", &military_HighBest_sigmoid_resultUSA::transport_aircraft_max,
        "transport_aircraft_norm", &military_HighBest_sigmoid_resultUSA::transport_aircraft_norm,
        "transport_aircraft_sigmoid", &military_HighBest_sigmoid_resultUSA::transport_aircraft_sigmoid,
        "military_bases_overseas", &military_HighBest_sigmoid_resultUSA::military_bases_overseas,
        "military_bases_overseas_min", &military_HighBest_sigmoid_resultUSA::military_bases_overseas_min,
        "military_bases_overseas_max", &military_HighBest_sigmoid_resultUSA::military_bases_overseas_max,
        "military_bases_overseas_norm", &military_HighBest_sigmoid_resultUSA::military_bases_overseas_norm,
        "military_bases_overseas_sigmoid", &military_HighBest_sigmoid_resultUSA::military_bases_overseas_sigmoid
    );

    lua.new_usertype<resources_HighBest_sigmoid_resultUSA>("resources_HighBest_sigmoid_resultUSA",
        "oil_reserves_billion_barrels", &resources_HighBest_sigmoid_resultUSA::oil_reserves_billion_barrels,
        "oil_reserves_billion_barrels_min", &resources_HighBest_sigmoid_resultUSA::oil_reserves_billion_barrels_min,
        "oil_reserves_billion_barrels_max", &resources_HighBest_sigmoid_resultUSA::oil_reserves_billion_barrels_max,
        "oil_reserves_billion_barrels_norm", &resources_HighBest_sigmoid_resultUSA::oil_reserves_billion_barrels_norm,
        "oil_reserves_billion_barrels_sigmoid", &resources_HighBest_sigmoid_resultUSA::oil_reserves_billion_barrels_sigmoid,
        "gas_reserves_tcf", &resources_HighBest_sigmoid_resultUSA::gas_reserves_tcf,
        "gas_reserves_tcf_min", &resources_HighBest_sigmoid_resultUSA::gas_reserves_tcf_min,
        "gas_reserves_tcf_max", &resources_HighBest_sigmoid_resultUSA::gas_reserves_tcf_max,
        "gas_reserves_tcf_norm", &resources_HighBest_sigmoid_resultUSA::gas_reserves_tcf_norm,
        "gas_reserves_tcf_sigmoid", &resources_HighBest_sigmoid_resultUSA::gas_reserves_tcf_sigmoid,
        "coal_reserves_billion_short_tons", &resources_HighBest_sigmoid_resultUSA::coal_reserves_billion_short_tons,
        "coal_reserves_billion_short_tons_min", &resources_HighBest_sigmoid_resultUSA::coal_reserves_billion_short_tons_min,
        "coal_reserves_billion_short_tons_max", &resources_HighBest_sigmoid_resultUSA::coal_reserves_billion_short_tons_max,
        "coal_reserves_billion_short_tons_norm", &resources_HighBest_sigmoid_resultUSA::coal_reserves_billion_short_tons_norm,
        "coal_reserves_billion_short_tons_sigmoid", &resources_HighBest_sigmoid_resultUSA::coal_reserves_billion_short_tons_sigmoid,
        "oil_production_bpd", &resources_HighBest_sigmoid_resultUSA::oil_production_bpd,
        "oil_production_bpd_min", &resources_HighBest_sigmoid_resultUSA::oil_production_bpd_min,
        "oil_production_bpd_max", &resources_HighBest_sigmoid_resultUSA::oil_production_bpd_max,
        "oil_production_bpd_norm", &resources_HighBest_sigmoid_resultUSA::oil_production_bpd_norm,
        "oil_production_bpd_sigmoid", &resources_HighBest_sigmoid_resultUSA::oil_production_bpd_sigmoid,
        "natural_gas_production_bcf_day", &resources_HighBest_sigmoid_resultUSA::natural_gas_production_bcf_day,
        "natural_gas_production_bcf_day_min", &resources_HighBest_sigmoid_resultUSA::natural_gas_production_bcf_day_min,
        "natural_gas_production_bcf_day_max", &resources_HighBest_sigmoid_resultUSA::natural_gas_production_bcf_day_max,
        "natural_gas_production_bcf_day_norm", &resources_HighBest_sigmoid_resultUSA::natural_gas_production_bcf_day_norm,
        "natural_gas_production_bcf_day_sigmoid", &resources_HighBest_sigmoid_resultUSA::natural_gas_production_bcf_day_sigmoid,
        "coal_production_million_short_tons", &resources_HighBest_sigmoid_resultUSA::coal_production_million_short_tons,
        "coal_production_million_short_tons_min", &resources_HighBest_sigmoid_resultUSA::coal_production_million_short_tons_min,
        "coal_production_million_short_tons_max", &resources_HighBest_sigmoid_resultUSA::coal_production_million_short_tons_max,
        "coal_production_million_short_tons_norm", &resources_HighBest_sigmoid_resultUSA::coal_production_million_short_tons_norm,
        "coal_production_million_short_tons_sigmoid", &resources_HighBest_sigmoid_resultUSA::coal_production_million_short_tons_sigmoid,
        "electricity_generation_twh", &resources_HighBest_sigmoid_resultUSA::electricity_generation_twh,
        "electricity_generation_twh_min", &resources_HighBest_sigmoid_resultUSA::electricity_generation_twh_min,
        "electricity_generation_twh_max", &resources_HighBest_sigmoid_resultUSA::electricity_generation_twh_max,
        "electricity_generation_twh_norm", &resources_HighBest_sigmoid_resultUSA::electricity_generation_twh_norm,
        "electricity_generation_twh_sigmoid", &resources_HighBest_sigmoid_resultUSA::electricity_generation_twh_sigmoid,
        "renewable_share", &resources_HighBest_sigmoid_resultUSA::renewable_share,
        "renewable_share_min", &resources_HighBest_sigmoid_resultUSA::renewable_share_min,
        "renewable_share_max", &resources_HighBest_sigmoid_resultUSA::renewable_share_max,
        "renewable_share_norm", &resources_HighBest_sigmoid_resultUSA::renewable_share_norm,
        "renewable_share_sigmoid", &resources_HighBest_sigmoid_resultUSA::renewable_share_sigmoid,
        "nuclear_share", &resources_HighBest_sigmoid_resultUSA::nuclear_share,
        "nuclear_share_min", &resources_HighBest_sigmoid_resultUSA::nuclear_share_min,
        "nuclear_share_max", &resources_HighBest_sigmoid_resultUSA::nuclear_share_max,
        "nuclear_share_norm", &resources_HighBest_sigmoid_resultUSA::nuclear_share_norm,
        "nuclear_share_sigmoid", &resources_HighBest_sigmoid_resultUSA::nuclear_share_sigmoid,
        "forest_area_km2", &resources_HighBest_sigmoid_resultUSA::forest_area_km2,
        "forest_area_km2_min", &resources_HighBest_sigmoid_resultUSA::forest_area_km2_min,
        "forest_area_km2_max", &resources_HighBest_sigmoid_resultUSA::forest_area_km2_max,
        "forest_area_km2_norm", &resources_HighBest_sigmoid_resultUSA::forest_area_km2_norm,
        "forest_area_km2_sigmoid", &resources_HighBest_sigmoid_resultUSA::forest_area_km2_sigmoid,
        "farmland_million_acres", &resources_HighBest_sigmoid_resultUSA::farmland_million_acres,
        "farmland_million_acres_min", &resources_HighBest_sigmoid_resultUSA::farmland_million_acres_min,
        "farmland_million_acres_max", &resources_HighBest_sigmoid_resultUSA::farmland_million_acres_max,
        "farmland_million_acres_norm", &resources_HighBest_sigmoid_resultUSA::farmland_million_acres_norm,
        "farmland_million_acres_sigmoid", &resources_HighBest_sigmoid_resultUSA::farmland_million_acres_sigmoid
    );

    lua.new_usertype<resources_LowBest_sigmoid_resultUSA>("resources_LowBest_sigmoid_resultUSA",
        "freshwater_withdrawal_bcm", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm,
        "freshwater_withdrawal_bcm_min", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm_min,
        "freshwater_withdrawal_bcm_max", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm_max,
        "freshwater_withdrawal_bcm_norm", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm_norm,
        "freshwater_withdrawal_bcm_sigmoid", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm_sigmoid,
        "co2_emissions_mt", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt,
        "co2_emissions_mt_min", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt_min,
        "co2_emissions_mt_max", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt_max,
        "co2_emissions_mt_norm", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt_norm,
        "co2_emissions_mt_sigmoid", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt_sigmoid
    );

    lua.new_usertype<infrastructure_HighBest_sigmoid_resultUSA>("infrastructure_HighBest_sigmoid_resultUSA",
        "land_area_km2", &infrastructure_HighBest_sigmoid_resultUSA::land_area_km2,
        "land_area_km2_min", &infrastructure_HighBest_sigmoid_resultUSA::land_area_km2_min,
        "land_area_km2_max", &infrastructure_HighBest_sigmoid_resultUSA::land_area_km2_max,
        "land_area_km2_norm", &infrastructure_HighBest_sigmoid_resultUSA::land_area_km2_norm,
        "land_area_km2_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::land_area_km2_sigmoid,
        "total_area_km2", &infrastructure_HighBest_sigmoid_resultUSA::total_area_km2,
        "total_area_km2_min", &infrastructure_HighBest_sigmoid_resultUSA::total_area_km2_min,
        "total_area_km2_max", &infrastructure_HighBest_sigmoid_resultUSA::total_area_km2_max,
        "total_area_km2_norm", &infrastructure_HighBest_sigmoid_resultUSA::total_area_km2_norm,
        "total_area_km2_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::total_area_km2_sigmoid,
        "coastline_km", &infrastructure_HighBest_sigmoid_resultUSA::coastline_km,
        "coastline_km_min", &infrastructure_HighBest_sigmoid_resultUSA::coastline_km_min,
        "coastline_km_max", &infrastructure_HighBest_sigmoid_resultUSA::coastline_km_max,
        "coastline_km_norm", &infrastructure_HighBest_sigmoid_resultUSA::coastline_km_norm,
        "coastline_km_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::coastline_km_sigmoid,
        "road_km", &infrastructure_HighBest_sigmoid_resultUSA::road_km,
        "road_km_min", &infrastructure_HighBest_sigmoid_resultUSA::road_km_min,
        "road_km_max", &infrastructure_HighBest_sigmoid_resultUSA::road_km_max,
        "road_km_norm", &infrastructure_HighBest_sigmoid_resultUSA::road_km_norm,
        "road_km_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::road_km_sigmoid,
        "rail_km", &infrastructure_HighBest_sigmoid_resultUSA::rail_km,
        "rail_km_min", &infrastructure_HighBest_sigmoid_resultUSA::rail_km_min,
        "rail_km_max", &infrastructure_HighBest_sigmoid_resultUSA::rail_km_max,
        "rail_km_norm", &infrastructure_HighBest_sigmoid_resultUSA::rail_km_norm,
        "rail_km_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::rail_km_sigmoid,
        "airports", &infrastructure_HighBest_sigmoid_resultUSA::airports,
        "airports_min", &infrastructure_HighBest_sigmoid_resultUSA::airports_min,
        "airports_max", &infrastructure_HighBest_sigmoid_resultUSA::airports_max,
        "airports_norm", &infrastructure_HighBest_sigmoid_resultUSA::airports_norm,
        "airports_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::airports_sigmoid,
        "major_ports", &infrastructure_HighBest_sigmoid_resultUSA::major_ports,
        "major_ports_min", &infrastructure_HighBest_sigmoid_resultUSA::major_ports_min,
        "major_ports_max", &infrastructure_HighBest_sigmoid_resultUSA::major_ports_max,
        "major_ports_norm", &infrastructure_HighBest_sigmoid_resultUSA::major_ports_norm,
        "major_ports_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::major_ports_sigmoid,
        "electricity_access_pct", &infrastructure_HighBest_sigmoid_resultUSA::electricity_access_pct,
        "electricity_access_pct_min", &infrastructure_HighBest_sigmoid_resultUSA::electricity_access_pct_min,
        "electricity_access_pct_max", &infrastructure_HighBest_sigmoid_resultUSA::electricity_access_pct_max,
        "electricity_access_pct_norm", &infrastructure_HighBest_sigmoid_resultUSA::electricity_access_pct_norm,
        "electricity_access_pct_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::electricity_access_pct_sigmoid,
        "safe_water_access_pct", &infrastructure_HighBest_sigmoid_resultUSA::safe_water_access_pct,
        "safe_water_access_pct_min", &infrastructure_HighBest_sigmoid_resultUSA::safe_water_access_pct_min,
        "safe_water_access_pct_max", &infrastructure_HighBest_sigmoid_resultUSA::safe_water_access_pct_max,
        "safe_water_access_pct_norm", &infrastructure_HighBest_sigmoid_resultUSA::safe_water_access_pct_norm,
        "safe_water_access_pct_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::safe_water_access_pct_sigmoid,
        "fixed_broadband_subscriptions", &infrastructure_HighBest_sigmoid_resultUSA::fixed_broadband_subscriptions,
        "fixed_broadband_subscriptions_min", &infrastructure_HighBest_sigmoid_resultUSA::fixed_broadband_subscriptions_min,
        "fixed_broadband_subscriptions_max", &infrastructure_HighBest_sigmoid_resultUSA::fixed_broadband_subscriptions_max,
        "fixed_broadband_subscriptions_norm", &infrastructure_HighBest_sigmoid_resultUSA::fixed_broadband_subscriptions_norm,
        "fixed_broadband_subscriptions_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::fixed_broadband_subscriptions_sigmoid,
        "mobile_subscriptions", &infrastructure_HighBest_sigmoid_resultUSA::mobile_subscriptions,
        "mobile_subscriptions_min", &infrastructure_HighBest_sigmoid_resultUSA::mobile_subscriptions_min,
        "mobile_subscriptions_max", &infrastructure_HighBest_sigmoid_resultUSA::mobile_subscriptions_max,
        "mobile_subscriptions_norm", &infrastructure_HighBest_sigmoid_resultUSA::mobile_subscriptions_norm,
        "mobile_subscriptions_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::mobile_subscriptions_sigmoid,
        "housing_units", &infrastructure_HighBest_sigmoid_resultUSA::housing_units,
        "housing_units_min", &infrastructure_HighBest_sigmoid_resultUSA::housing_units_min,
        "housing_units_max", &infrastructure_HighBest_sigmoid_resultUSA::housing_units_max,
        "housing_units_norm", &infrastructure_HighBest_sigmoid_resultUSA::housing_units_norm,
        "housing_units_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::housing_units_sigmoid,
        "data_centers", &infrastructure_HighBest_sigmoid_resultUSA::data_centers,
        "data_centers_min", &infrastructure_HighBest_sigmoid_resultUSA::data_centers_min,
        "data_centers_max", &infrastructure_HighBest_sigmoid_resultUSA::data_centers_max,
        "data_centers_norm", &infrastructure_HighBest_sigmoid_resultUSA::data_centers_norm,
        "data_centers_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::data_centers_sigmoid
    );

    lua.new_usertype<education_HighBest_sigmoid_resultUSA>("education_HighBest_sigmoid_resultUSA",
        "literacy_rate", &education_HighBest_sigmoid_resultUSA::literacy_rate,
        "literacy_rate_min", &education_HighBest_sigmoid_resultUSA::literacy_rate_min,
        "literacy_rate_max", &education_HighBest_sigmoid_resultUSA::literacy_rate_max,
        "literacy_rate_norm", &education_HighBest_sigmoid_resultUSA::literacy_rate_norm,
        "literacy_rate_sigmoid", &education_HighBest_sigmoid_resultUSA::literacy_rate_sigmoid,
        "education_spending_pct_gdp", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp,
        "education_spending_pct_gdp_min", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp_min,
        "education_spending_pct_gdp_max", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp_max,
        "education_spending_pct_gdp_norm", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp_norm,
        "education_spending_pct_gdp_sigmoid", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp_sigmoid,
        "school_life_expectancy", &education_HighBest_sigmoid_resultUSA::school_life_expectancy,
        "school_life_expectancy_min", &education_HighBest_sigmoid_resultUSA::school_life_expectancy_min,
        "school_life_expectancy_max", &education_HighBest_sigmoid_resultUSA::school_life_expectancy_max,
        "school_life_expectancy_norm", &education_HighBest_sigmoid_resultUSA::school_life_expectancy_norm,
        "school_life_expectancy_sigmoid", &education_HighBest_sigmoid_resultUSA::school_life_expectancy_sigmoid,
        "high_school_graduation_rate", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate,
        "high_school_graduation_rate_min", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate_min,
        "high_school_graduation_rate_max", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate_max,
        "high_school_graduation_rate_norm", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate_norm,
        "high_school_graduation_rate_sigmoid", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate_sigmoid,
        "tertiary_attainment_pct", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct,
        "tertiary_attainment_pct_min", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct_min,
        "tertiary_attainment_pct_max", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct_max,
        "tertiary_attainment_pct_norm", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct_norm,
        "tertiary_attainment_pct_sigmoid", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct_sigmoid,
        "public_school_students", &education_HighBest_sigmoid_resultUSA::public_school_students,
        "public_school_students_min", &education_HighBest_sigmoid_resultUSA::public_school_students_min,
        "public_school_students_max", &education_HighBest_sigmoid_resultUSA::public_school_students_max,
        "public_school_students_norm", &education_HighBest_sigmoid_resultUSA::public_school_students_norm,
        "public_school_students_sigmoid", &education_HighBest_sigmoid_resultUSA::public_school_students_sigmoid,
        "college_students", &education_HighBest_sigmoid_resultUSA::college_students,
        "college_students_min", &education_HighBest_sigmoid_resultUSA::college_students_min,
        "college_students_max", &education_HighBest_sigmoid_resultUSA::college_students_max,
        "college_students_norm", &education_HighBest_sigmoid_resultUSA::college_students_norm,
        "college_students_sigmoid", &education_HighBest_sigmoid_resultUSA::college_students_sigmoid,
        "stem_graduates_yearly", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly,
        "stem_graduates_yearly_min", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly_min,
        "stem_graduates_yearly_max", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly_max,
        "stem_graduates_yearly_norm", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly_norm,
        "stem_graduates_yearly_sigmoid", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly_sigmoid
    );

    lua.new_usertype<health_HighBest_sigmoid_resultUSA>("health_HighBest_sigmoid_resultUSA",
        "health_spending_pct_gdp", &health_HighBest_sigmoid_resultUSA::health_spending_pct_gdp,
        "health_spending_pct_gdp_min", &health_HighBest_sigmoid_resultUSA::health_spending_pct_gdp_min,
        "health_spending_pct_gdp_max", &health_HighBest_sigmoid_resultUSA::health_spending_pct_gdp_max,
        "health_spending_pct_gdp_norm", &health_HighBest_sigmoid_resultUSA::health_spending_pct_gdp_norm,
        "health_spending_pct_gdp_sigmoid", &health_HighBest_sigmoid_resultUSA::health_spending_pct_gdp_sigmoid,
        "insured_rate", &health_HighBest_sigmoid_resultUSA::insured_rate,
        "insured_rate_min", &health_HighBest_sigmoid_resultUSA::insured_rate_min,
        "insured_rate_max", &health_HighBest_sigmoid_resultUSA::insured_rate_max,
        "insured_rate_norm", &health_HighBest_sigmoid_resultUSA::insured_rate_norm,
        "insured_rate_sigmoid", &health_HighBest_sigmoid_resultUSA::insured_rate_sigmoid,
        "physicians_per_1000", &health_HighBest_sigmoid_resultUSA::physicians_per_1000,
        "physicians_per_1000_min", &health_HighBest_sigmoid_resultUSA::physicians_per_1000_min,
        "physicians_per_1000_max", &health_HighBest_sigmoid_resultUSA::physicians_per_1000_max,
        "physicians_per_1000_norm", &health_HighBest_sigmoid_resultUSA::physicians_per_1000_norm,
        "physicians_per_1000_sigmoid", &health_HighBest_sigmoid_resultUSA::physicians_per_1000_sigmoid,
        "hospital_beds_per_1000", &health_HighBest_sigmoid_resultUSA::hospital_beds_per_1000,
        "hospital_beds_per_1000_min", &health_HighBest_sigmoid_resultUSA::hospital_beds_per_1000_min,
        "hospital_beds_per_1000_max", &health_HighBest_sigmoid_resultUSA::hospital_beds_per_1000_max,
        "hospital_beds_per_1000_norm", &health_HighBest_sigmoid_resultUSA::hospital_beds_per_1000_norm,
        "hospital_beds_per_1000_sigmoid", &health_HighBest_sigmoid_resultUSA::hospital_beds_per_1000_sigmoid,
        "nurses", &health_HighBest_sigmoid_resultUSA::nurses,
        "nurses_min", &health_HighBest_sigmoid_resultUSA::nurses_min,
        "nurses_max", &health_HighBest_sigmoid_resultUSA::nurses_max,
        "nurses_norm", &health_HighBest_sigmoid_resultUSA::nurses_norm,
        "nurses_sigmoid", &health_HighBest_sigmoid_resultUSA::nurses_sigmoid,
        "hospital_count", &health_HighBest_sigmoid_resultUSA::hospital_count,
        "hospital_count_min", &health_HighBest_sigmoid_resultUSA::hospital_count_min,
        "hospital_count_max", &health_HighBest_sigmoid_resultUSA::hospital_count_max,
        "hospital_count_norm", &health_HighBest_sigmoid_resultUSA::hospital_count_norm,
        "hospital_count_sigmoid", &health_HighBest_sigmoid_resultUSA::hospital_count_sigmoid
    );

    lua.new_usertype<health_LowBest_sigmoid_resultUSA>("health_LowBest_sigmoid_resultUSA",
        "obesity_rate", &health_LowBest_sigmoid_resultUSA::obesity_rate,
        "obesity_rate_min", &health_LowBest_sigmoid_resultUSA::obesity_rate_min,
        "obesity_rate_max", &health_LowBest_sigmoid_resultUSA::obesity_rate_max,
        "obesity_rate_norm", &health_LowBest_sigmoid_resultUSA::obesity_rate_norm,
        "obesity_rate_sigmoid", &health_LowBest_sigmoid_resultUSA::obesity_rate_sigmoid,
        "maternal_mortality", &health_LowBest_sigmoid_resultUSA::maternal_mortality,
        "maternal_mortality_min", &health_LowBest_sigmoid_resultUSA::maternal_mortality_min,
        "maternal_mortality_max", &health_LowBest_sigmoid_resultUSA::maternal_mortality_max,
        "maternal_mortality_norm", &health_LowBest_sigmoid_resultUSA::maternal_mortality_norm,
        "maternal_mortality_sigmoid", &health_LowBest_sigmoid_resultUSA::maternal_mortality_sigmoid
    );

    lua.new_usertype<technology_HighBest_sigmoid_resultUSA>("technology_HighBest_sigmoid_resultUSA",
        "rnd_spending", &technology_HighBest_sigmoid_resultUSA::rnd_spending,
        "rnd_spending_min", &technology_HighBest_sigmoid_resultUSA::rnd_spending_min,
        "rnd_spending_max", &technology_HighBest_sigmoid_resultUSA::rnd_spending_max,
        "rnd_spending_norm", &technology_HighBest_sigmoid_resultUSA::rnd_spending_norm,
        "rnd_spending_sigmoid", &technology_HighBest_sigmoid_resultUSA::rnd_spending_sigmoid,
        "rnd_share_gdp", &technology_HighBest_sigmoid_resultUSA::rnd_share_gdp,
        "rnd_share_gdp_min", &technology_HighBest_sigmoid_resultUSA::rnd_share_gdp_min,
        "rnd_share_gdp_max", &technology_HighBest_sigmoid_resultUSA::rnd_share_gdp_max,
        "rnd_share_gdp_norm", &technology_HighBest_sigmoid_resultUSA::rnd_share_gdp_norm,
        "rnd_share_gdp_sigmoid", &technology_HighBest_sigmoid_resultUSA::rnd_share_gdp_sigmoid,
        "internet_users_pct", &technology_HighBest_sigmoid_resultUSA::internet_users_pct,
        "internet_users_pct_min", &technology_HighBest_sigmoid_resultUSA::internet_users_pct_min,
        "internet_users_pct_max", &technology_HighBest_sigmoid_resultUSA::internet_users_pct_max,
        "internet_users_pct_norm", &technology_HighBest_sigmoid_resultUSA::internet_users_pct_norm,
        "internet_users_pct_sigmoid", &technology_HighBest_sigmoid_resultUSA::internet_users_pct_sigmoid,
        "smartphone_users_pct", &technology_HighBest_sigmoid_resultUSA::smartphone_users_pct,
        "smartphone_users_pct_min", &technology_HighBest_sigmoid_resultUSA::smartphone_users_pct_min,
        "smartphone_users_pct_max", &technology_HighBest_sigmoid_resultUSA::smartphone_users_pct_max,
        "smartphone_users_pct_norm", &technology_HighBest_sigmoid_resultUSA::smartphone_users_pct_norm,
        "smartphone_users_pct_sigmoid", &technology_HighBest_sigmoid_resultUSA::smartphone_users_pct_sigmoid,
        "cloud_market_size", &technology_HighBest_sigmoid_resultUSA::cloud_market_size,
        "cloud_market_size_min", &technology_HighBest_sigmoid_resultUSA::cloud_market_size_min,
        "cloud_market_size_max", &technology_HighBest_sigmoid_resultUSA::cloud_market_size_max,
        "cloud_market_size_norm", &technology_HighBest_sigmoid_resultUSA::cloud_market_size_norm,
        "cloud_market_size_sigmoid", &technology_HighBest_sigmoid_resultUSA::cloud_market_size_sigmoid,
        "ai_private_investment", &technology_HighBest_sigmoid_resultUSA::ai_private_investment,
        "ai_private_investment_min", &technology_HighBest_sigmoid_resultUSA::ai_private_investment_min,
        "ai_private_investment_max", &technology_HighBest_sigmoid_resultUSA::ai_private_investment_max,
        "ai_private_investment_norm", &technology_HighBest_sigmoid_resultUSA::ai_private_investment_norm,
        "ai_private_investment_sigmoid", &technology_HighBest_sigmoid_resultUSA::ai_private_investment_sigmoid,
        "space_launches_yearly", &technology_HighBest_sigmoid_resultUSA::space_launches_yearly,
        "space_launches_yearly_min", &technology_HighBest_sigmoid_resultUSA::space_launches_yearly_min,
        "space_launches_yearly_max", &technology_HighBest_sigmoid_resultUSA::space_launches_yearly_max,
        "space_launches_yearly_norm", &technology_HighBest_sigmoid_resultUSA::space_launches_yearly_norm,
        "space_launches_yearly_sigmoid", &technology_HighBest_sigmoid_resultUSA::space_launches_yearly_sigmoid,
        "patents_granted_yearly", &technology_HighBest_sigmoid_resultUSA::patents_granted_yearly,
        "patents_granted_yearly_min", &technology_HighBest_sigmoid_resultUSA::patents_granted_yearly_min,
        "patents_granted_yearly_max", &technology_HighBest_sigmoid_resultUSA::patents_granted_yearly_max,
        "patents_granted_yearly_norm", &technology_HighBest_sigmoid_resultUSA::patents_granted_yearly_norm,
        "patents_granted_yearly_sigmoid", &technology_HighBest_sigmoid_resultUSA::patents_granted_yearly_sigmoid
    );

    lua.new_usertype<UtilityUSAConfig>("UtilityUSAConfig",
        "country", &UtilityUSAConfig::country,
        "government_sigmoid_result", &UtilityUSAConfig::government_sigmoid_result,
        "demography_highbest_sigmoid_result", &UtilityUSAConfig::demography_highbest_sigmoid_result,
        "demography_lowbest_sigmoid_result", &UtilityUSAConfig::demography_lowbest_sigmoid_result,
        "economy_highbest_sigmoid_result", &UtilityUSAConfig::economy_highbest_sigmoid_result,
        "economy_lowbest_sigmoid_result", &UtilityUSAConfig::economy_lowbest_sigmoid_result,
        "government_highbest_sigmoid_result", &UtilityUSAConfig::government_highbest_sigmoid_result,
        "government_lowbest_sigmoid_result", &UtilityUSAConfig::government_lowbest_sigmoid_result,
        "military_highbest_sigmoid_result", &UtilityUSAConfig::military_highbest_sigmoid_result,
        "resources_highbest_sigmoid_result", &UtilityUSAConfig::resources_highbest_sigmoid_result,
        "resources_lowbest_sigmoid_result", &UtilityUSAConfig::resources_lowbest_sigmoid_result,
        "infrastructure_highbest_sigmoid_result", &UtilityUSAConfig::infrastructure_highbest_sigmoid_result,
        "education_highbest_sigmoid_result", &UtilityUSAConfig::education_highbest_sigmoid_result,
        "health_highbest_sigmoid_result", &UtilityUSAConfig::health_highbest_sigmoid_result,
        "health_lowbest_sigmoid_result", &UtilityUSAConfig::health_lowbest_sigmoid_result,
        "technology_highbest_sigmoid_result", &UtilityUSAConfig::technology_highbest_sigmoid_result
    );

    lua.new_usertype<kingdom_infoMagic>("kingdom_infoMagic",
        "name", &kingdom_infoMagic::name,
        "founded_year", &kingdom_infoMagic::founded_year,
        "capital", &kingdom_infoMagic::capital,
        "ruling_house", &kingdom_infoMagic::ruling_house,
        "current_monarch", &kingdom_infoMagic::current_monarch,
        "government_type", &kingdom_infoMagic::government_type
    );

    lua.new_usertype<government_HighBest_sigmoid_resultMagic>("government_HighBest_sigmoid_resultMagic",
        "approval_rating", &government_HighBest_sigmoid_resultMagic::approval_rating,
        "approval_rating_min", &government_HighBest_sigmoid_resultMagic::approval_rating_min,
        "approval_rating_max", &government_HighBest_sigmoid_resultMagic::approval_rating_max,
        "approval_rating_norm", &government_HighBest_sigmoid_resultMagic::approval_rating_norm,
        "approval_rating_sigmoid", &government_HighBest_sigmoid_resultMagic::approval_rating_sigmoid
    );

    lua.new_usertype<government_LowBest_sigmoid_resultMagic>("government_LowBest_sigmoid_resultMagic",
        "tax_burden_index", &government_LowBest_sigmoid_resultMagic::tax_burden_index,
        "tax_burden_index_min", &government_LowBest_sigmoid_resultMagic::tax_burden_index_min,
        "tax_burden_index_max", &government_LowBest_sigmoid_resultMagic::tax_burden_index_max,
        "tax_burden_index_norm", &government_LowBest_sigmoid_resultMagic::tax_burden_index_norm,
        "tax_burden_index_sigmoid", &government_LowBest_sigmoid_resultMagic::tax_burden_index_sigmoid
    );

    lua.new_usertype<magic_HighBest_sigmoid_resultMagic>("magic_HighBest_sigmoid_resultMagic",
        "mana_saturation", &magic_HighBest_sigmoid_resultMagic::mana_saturation,
        "mana_saturation_min", &magic_HighBest_sigmoid_resultMagic::mana_saturation_min,
        "mana_saturation_max", &magic_HighBest_sigmoid_resultMagic::mana_saturation_max,
        "mana_saturation_norm", &magic_HighBest_sigmoid_resultMagic::mana_saturation_norm,
        "mana_saturation_sigmoid", &magic_HighBest_sigmoid_resultMagic::mana_saturation_sigmoid
    );

    lua.new_usertype<magic_LowBest_sigmoid_resultMagic>("magic_LowBest_sigmoid_resultMagic",
        "forbidden_magic_incidents", &magic_LowBest_sigmoid_resultMagic::forbidden_magic_incidents,
        "forbidden_magic_incidents_min", &magic_LowBest_sigmoid_resultMagic::forbidden_magic_incidents_min,
        "forbidden_magic_incidents_max", &magic_LowBest_sigmoid_resultMagic::forbidden_magic_incidents_max,
        "forbidden_magic_incidents_norm", &magic_LowBest_sigmoid_resultMagic::forbidden_magic_incidents_norm,
        "forbidden_magic_incidents_sigmoid", &magic_LowBest_sigmoid_resultMagic::forbidden_magic_incidents_sigmoid
    );

    lua.new_usertype<population_LowBest_sigmoid_resultMagic>("population_LowBest_sigmoid_resultMagic",
        "total_population", &population_LowBest_sigmoid_resultMagic::total_population,
        "total_population_min", &population_LowBest_sigmoid_resultMagic::total_population_min,
        "total_population_max", &population_LowBest_sigmoid_resultMagic::total_population_max,
        "total_population_norm", &population_LowBest_sigmoid_resultMagic::total_population_norm,
        "total_population_sigmoid", &population_LowBest_sigmoid_resultMagic::total_population_sigmoid
    );

    lua.new_usertype<population_HighBest_sigmoid_resultMagic>("population_HighBest_sigmoid_resultMagic",
        "mage_population_ratio", &population_HighBest_sigmoid_resultMagic::mage_population_ratio,
        "mage_population_ratio_min", &population_HighBest_sigmoid_resultMagic::mage_population_ratio_min,
        "mage_population_ratio_max", &population_HighBest_sigmoid_resultMagic::mage_population_ratio_max,
        "mage_population_ratio_norm", &population_HighBest_sigmoid_resultMagic::mage_population_ratio_norm,
        "mage_population_ratio_sigmoid", &population_HighBest_sigmoid_resultMagic::mage_population_ratio_sigmoid
    );

    lua.new_usertype<economy_HighBest_sigmoid_resultMagic>("economy_HighBest_sigmoid_resultMagic",
        "gdp_gold_standard", &economy_HighBest_sigmoid_resultMagic::gdp_gold_standard,
        "gdp_gold_standard_min", &economy_HighBest_sigmoid_resultMagic::gdp_gold_standard_min,
        "gdp_gold_standard_max", &economy_HighBest_sigmoid_resultMagic::gdp_gold_standard_max,
        "gdp_gold_standard_norm", &economy_HighBest_sigmoid_resultMagic::gdp_gold_standard_norm,
        "gdp_gold_standard_sigmoid", &economy_HighBest_sigmoid_resultMagic::gdp_gold_standard_sigmoid
    );

    lua.new_usertype<economy_LowBest_sigmoid_resultMagic>("economy_LowBest_sigmoid_resultMagic",
        "inflation_rate", &economy_LowBest_sigmoid_resultMagic::inflation_rate,
        "inflation_rate_min", &economy_LowBest_sigmoid_resultMagic::inflation_rate_min,
        "inflation_rate_max", &economy_LowBest_sigmoid_resultMagic::inflation_rate_max,
        "inflation_rate_norm", &economy_LowBest_sigmoid_resultMagic::inflation_rate_norm,
        "inflation_rate_sigmoid", &economy_LowBest_sigmoid_resultMagic::inflation_rate_sigmoid
    );

    lua.new_usertype<military_HighBest_sigmoid_resultMagic>("military_HighBest_sigmoid_resultMagic",
        "royal_battlemage_corps_strength", &military_HighBest_sigmoid_resultMagic::royal_battlemage_corps_strength,
        "royal_battlemage_corps_strength_min", &military_HighBest_sigmoid_resultMagic::royal_battlemage_corps_strength_min,
        "royal_battlemage_corps_strength_max", &military_HighBest_sigmoid_resultMagic::royal_battlemage_corps_strength_max,
        "royal_battlemage_corps_strength_norm", &military_HighBest_sigmoid_resultMagic::royal_battlemage_corps_strength_norm,
        "royal_battlemage_corps_strength_sigmoid", &military_HighBest_sigmoid_resultMagic::royal_battlemage_corps_strength_sigmoid
    );

    lua.new_usertype<military_LowBest_sigmoid_resultMagic>("military_LowBest_sigmoid_resultMagic",
        "border_conflict_frequency", &military_LowBest_sigmoid_resultMagic::border_conflict_frequency,
        "border_conflict_frequency_min", &military_LowBest_sigmoid_resultMagic::border_conflict_frequency_min,
        "border_conflict_frequency_max", &military_LowBest_sigmoid_resultMagic::border_conflict_frequency_max,
        "border_conflict_frequency_norm", &military_LowBest_sigmoid_resultMagic::border_conflict_frequency_norm,
        "border_conflict_frequency_sigmoid", &military_LowBest_sigmoid_resultMagic::border_conflict_frequency_sigmoid
    );

    lua.new_usertype<environment_HighBest_sigmoid_resultMagic>("environment_HighBest_sigmoid_resultMagic",
        "starwood_forest_health", &environment_HighBest_sigmoid_resultMagic::starwood_forest_health,
        "starwood_forest_health_min", &environment_HighBest_sigmoid_resultMagic::starwood_forest_health_min,
        "starwood_forest_health_max", &environment_HighBest_sigmoid_resultMagic::starwood_forest_health_max,
        "starwood_forest_health_norm", &environment_HighBest_sigmoid_resultMagic::starwood_forest_health_norm,
        "starwood_forest_health_sigmoid", &environment_HighBest_sigmoid_resultMagic::starwood_forest_health_sigmoid
    );

    lua.new_usertype<environment_LowBest_sigmoid_resultMagic>("environment_LowBest_sigmoid_resultMagic",
        "leyline_instability", &environment_LowBest_sigmoid_resultMagic::leyline_instability,
        "leyline_instability_min", &environment_LowBest_sigmoid_resultMagic::leyline_instability_min,
        "leyline_instability_max", &environment_LowBest_sigmoid_resultMagic::leyline_instability_max,
        "leyline_instability_norm", &environment_LowBest_sigmoid_resultMagic::leyline_instability_norm,
        "leyline_instability_sigmoid", &environment_LowBest_sigmoid_resultMagic::leyline_instability_sigmoid
    );

    lua.new_usertype<diplomacy_HighBest_sigmoid_resultMagic>("diplomacy_HighBest_sigmoid_resultMagic",
        "neighboring_realms_relations", &diplomacy_HighBest_sigmoid_resultMagic::neighboring_realms_relations,
        "neighboring_realms_relations_min", &diplomacy_HighBest_sigmoid_resultMagic::neighboring_realms_relations_min,
        "neighboring_realms_relations_max", &diplomacy_HighBest_sigmoid_resultMagic::neighboring_realms_relations_max,
        "neighboring_realms_relations_norm", &diplomacy_HighBest_sigmoid_resultMagic::neighboring_realms_relations_norm,
        "neighboring_realms_relations_sigmoid", &diplomacy_HighBest_sigmoid_resultMagic::neighboring_realms_relations_sigmoid
    );

    lua.new_usertype<diplomacy_LowBest_sigmoid_resultMagic>("diplomacy_LowBest_sigmoid_resultMagic",
        "active_trade_disputes", &diplomacy_LowBest_sigmoid_resultMagic::active_trade_disputes,
        "active_trade_disputes_min", &diplomacy_LowBest_sigmoid_resultMagic::active_trade_disputes_min,
        "active_trade_disputes_max", &diplomacy_LowBest_sigmoid_resultMagic::active_trade_disputes_max,
        "active_trade_disputes_norm", &diplomacy_LowBest_sigmoid_resultMagic::active_trade_disputes_norm,
        "active_trade_disputes_sigmoid", &diplomacy_LowBest_sigmoid_resultMagic::active_trade_disputes_sigmoid
    );

    lua.new_usertype<culture_HighBest_sigmoid_resultMagic>("culture_HighBest_sigmoid_resultMagic",
        "festival_of_stars_attendance", &culture_HighBest_sigmoid_resultMagic::festival_of_stars_attendance,
        "festival_of_stars_attendance_min", &culture_HighBest_sigmoid_resultMagic::festival_of_stars_attendance_min,
        "festival_of_stars_attendance_max", &culture_HighBest_sigmoid_resultMagic::festival_of_stars_attendance_max,
        "festival_of_stars_attendance_norm", &culture_HighBest_sigmoid_resultMagic::festival_of_stars_attendance_norm,
        "festival_of_stars_attendance_sigmoid", &culture_HighBest_sigmoid_resultMagic::festival_of_stars_attendance_sigmoid
    );

    lua.new_usertype<infrastructure_HighBest_sigmoid_resultMagic>("infrastructure_HighBest_sigmoid_resultMagic",
        "teleportation_network_coverage", &infrastructure_HighBest_sigmoid_resultMagic::teleportation_network_coverage,
        "teleportation_network_coverage_min", &infrastructure_HighBest_sigmoid_resultMagic::teleportation_network_coverage_min,
        "teleportation_network_coverage_max", &infrastructure_HighBest_sigmoid_resultMagic::teleportation_network_coverage_max,
        "teleportation_network_coverage_norm", &infrastructure_HighBest_sigmoid_resultMagic::teleportation_network_coverage_norm,
        "teleportation_network_coverage_sigmoid", &infrastructure_HighBest_sigmoid_resultMagic::teleportation_network_coverage_sigmoid
    );

    lua.new_usertype<infrastructure_LowBest_sigmoid_resultMagic>("infrastructure_LowBest_sigmoid_resultMagic",
        "crumbling_ward_sites", &infrastructure_LowBest_sigmoid_resultMagic::crumbling_ward_sites,
        "crumbling_ward_sites_min", &infrastructure_LowBest_sigmoid_resultMagic::crumbling_ward_sites_min,
        "crumbling_ward_sites_max", &infrastructure_LowBest_sigmoid_resultMagic::crumbling_ward_sites_max,
        "crumbling_ward_sites_norm", &infrastructure_LowBest_sigmoid_resultMagic::crumbling_ward_sites_norm,
        "crumbling_ward_sites_sigmoid", &infrastructure_LowBest_sigmoid_resultMagic::crumbling_ward_sites_sigmoid
    );

    lua.new_usertype<UtilityMagicConfig>("UtilityMagicConfig",
        "kingdom_info", &UtilityMagicConfig::kingdom_info,
        "government_highbest_sigmoid_result", &UtilityMagicConfig::government_highbest_sigmoid_result,
        "government_lowbest_sigmoid_result", &UtilityMagicConfig::government_lowbest_sigmoid_result,
        "magic_highbest_sigmoid_result", &UtilityMagicConfig::magic_highbest_sigmoid_result,
        "magic_lowbest_sigmoid_result", &UtilityMagicConfig::magic_lowbest_sigmoid_result,
        "population_lowbest_sigmoid_result", &UtilityMagicConfig::population_lowbest_sigmoid_result,
        "population_highbest_sigmoid_result", &UtilityMagicConfig::population_highbest_sigmoid_result,
        "economy_highbest_sigmoid_result", &UtilityMagicConfig::economy_highbest_sigmoid_result,
        "economy_lowbest_sigmoid_result", &UtilityMagicConfig::economy_lowbest_sigmoid_result,
        "military_highbest_sigmoid_result", &UtilityMagicConfig::military_highbest_sigmoid_result,
        "military_lowbest_sigmoid_result", &UtilityMagicConfig::military_lowbest_sigmoid_result,
        "environment_highbest_sigmoid_result", &UtilityMagicConfig::environment_highbest_sigmoid_result,
        "environment_lowbest_sigmoid_result", &UtilityMagicConfig::environment_lowbest_sigmoid_result,
        "diplomacy_highbest_sigmoid_result", &UtilityMagicConfig::diplomacy_highbest_sigmoid_result,
        "diplomacy_lowbest_sigmoid_result", &UtilityMagicConfig::diplomacy_lowbest_sigmoid_result,
        "culture_highbest_sigmoid_result", &UtilityMagicConfig::culture_highbest_sigmoid_result,
        "infrastructure_highbest_sigmoid_result", &UtilityMagicConfig::infrastructure_highbest_sigmoid_result,
        "infrastructure_lowbest_sigmoid_result", &UtilityMagicConfig::infrastructure_lowbest_sigmoid_result
    );

    lua.new_usertype<RootConfig>("RootConfig",
        "uSA", &RootConfig::uSA,
        "magic", &RootConfig::magic
    );
}