#include "RootLua.hpp"
#include <sol/sol.hpp>
#include "src/autoconfig/Root.hpp"

void LuaAuto::BindRootConfig_1(sol::state& lua)
{
    lua.new_usertype<resources_LowBest_sigmoid_resultUSA>("resources_LowBest_sigmoid_resultUSA",
        "freshwater_withdrawal_bcm", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm,
        "freshwater_withdrawal_bcm_min", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm_min,
        "freshwater_withdrawal_bcm_max", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm_max,
        "freshwater_withdrawal_bcm_norm", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm_norm,
        "freshwater_withdrawal_bcm_sigmoid", &resources_LowBest_sigmoid_resultUSA::freshwater_withdrawal_bcm_sigmoid,
        "co2_emissions_mt", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt,
        "co2_emissions_mt_min", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt_min,
        "co2_emissions_mt_max", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt_max,
        "co2_emissions_mt_norm", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt_norm,
        "co2_emissions_mt_sigmoid", &resources_LowBest_sigmoid_resultUSA::co2_emissions_mt_sigmoid
    );

    lua.new_usertype<infrastructure_HighBest_sigmoid_resultUSA>("infrastructure_HighBest_sigmoid_resultUSA",
        "land_area_km2", &infrastructure_HighBest_sigmoid_resultUSA::land_area_km2,
        "land_area_km2_min", &infrastructure_HighBest_sigmoid_resultUSA::land_area_km2_min,
        "land_area_km2_max", &infrastructure_HighBest_sigmoid_resultUSA::land_area_km2_max,
        "land_area_km2_norm", &infrastructure_HighBest_sigmoid_resultUSA::land_area_km2_norm,
        "land_area_km2_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::land_area_km2_sigmoid,
        "total_area_km2", &infrastructure_HighBest_sigmoid_resultUSA::total_area_km2,
        "total_area_km2_min", &infrastructure_HighBest_sigmoid_resultUSA::total_area_km2_min,
        "total_area_km2_max", &infrastructure_HighBest_sigmoid_resultUSA::total_area_km2_max,
        "total_area_km2_norm", &infrastructure_HighBest_sigmoid_resultUSA::total_area_km2_norm,
        "total_area_km2_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::total_area_km2_sigmoid,
        "coastline_km", &infrastructure_HighBest_sigmoid_resultUSA::coastline_km,
        "coastline_km_min", &infrastructure_HighBest_sigmoid_resultUSA::coastline_km_min,
        "coastline_km_max", &infrastructure_HighBest_sigmoid_resultUSA::coastline_km_max,
        "coastline_km_norm", &infrastructure_HighBest_sigmoid_resultUSA::coastline_km_norm,
        "coastline_km_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::coastline_km_sigmoid,
        "road_km", &infrastructure_HighBest_sigmoid_resultUSA::road_km,
        "road_km_min", &infrastructure_HighBest_sigmoid_resultUSA::road_km_min,
        "road_km_max", &infrastructure_HighBest_sigmoid_resultUSA::road_km_max,
        "road_km_norm", &infrastructure_HighBest_sigmoid_resultUSA::road_km_norm,
        "road_km_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::road_km_sigmoid,
        "rail_km", &infrastructure_HighBest_sigmoid_resultUSA::rail_km,
        "rail_km_min", &infrastructure_HighBest_sigmoid_resultUSA::rail_km_min,
        "rail_km_max", &infrastructure_HighBest_sigmoid_resultUSA::rail_km_max,
        "rail_km_norm", &infrastructure_HighBest_sigmoid_resultUSA::rail_km_norm,
        "rail_km_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::rail_km_sigmoid,
        "airports", &infrastructure_HighBest_sigmoid_resultUSA::airports,
        "airports_min", &infrastructure_HighBest_sigmoid_resultUSA::airports_min,
        "airports_max", &infrastructure_HighBest_sigmoid_resultUSA::airports_max,
        "airports_norm", &infrastructure_HighBest_sigmoid_resultUSA::airports_norm,
        "airports_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::airports_sigmoid,
        "major_ports", &infrastructure_HighBest_sigmoid_resultUSA::major_ports,
        "major_ports_min", &infrastructure_HighBest_sigmoid_resultUSA::major_ports_min,
        "major_ports_max", &infrastructure_HighBest_sigmoid_resultUSA::major_ports_max,
        "major_ports_norm", &infrastructure_HighBest_sigmoid_resultUSA::major_ports_norm,
        "major_ports_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::major_ports_sigmoid,
        "electricity_access_pct", &infrastructure_HighBest_sigmoid_resultUSA::electricity_access_pct,
        "electricity_access_pct_min", &infrastructure_HighBest_sigmoid_resultUSA::electricity_access_pct_min,
        "electricity_access_pct_max", &infrastructure_HighBest_sigmoid_resultUSA::electricity_access_pct_max,
        "electricity_access_pct_norm", &infrastructure_HighBest_sigmoid_resultUSA::electricity_access_pct_norm,
        "electricity_access_pct_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::electricity_access_pct_sigmoid,
        "safe_water_access_pct", &infrastructure_HighBest_sigmoid_resultUSA::safe_water_access_pct,
        "safe_water_access_pct_min", &infrastructure_HighBest_sigmoid_resultUSA::safe_water_access_pct_min,
        "safe_water_access_pct_max", &infrastructure_HighBest_sigmoid_resultUSA::safe_water_access_pct_max,
        "safe_water_access_pct_norm", &infrastructure_HighBest_sigmoid_resultUSA::safe_water_access_pct_norm,
        "safe_water_access_pct_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::safe_water_access_pct_sigmoid,
        "fixed_broadband_subscriptions", &infrastructure_HighBest_sigmoid_resultUSA::fixed_broadband_subscriptions,
        "fixed_broadband_subscriptions_min", &infrastructure_HighBest_sigmoid_resultUSA::fixed_broadband_subscriptions_min,
        "fixed_broadband_subscriptions_max", &infrastructure_HighBest_sigmoid_resultUSA::fixed_broadband_subscriptions_max,
        "fixed_broadband_subscriptions_norm", &infrastructure_HighBest_sigmoid_resultUSA::fixed_broadband_subscriptions_norm,
        "fixed_broadband_subscriptions_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::fixed_broadband_subscriptions_sigmoid,
        "mobile_subscriptions", &infrastructure_HighBest_sigmoid_resultUSA::mobile_subscriptions,
        "mobile_subscriptions_min", &infrastructure_HighBest_sigmoid_resultUSA::mobile_subscriptions_min,
        "mobile_subscriptions_max", &infrastructure_HighBest_sigmoid_resultUSA::mobile_subscriptions_max,
        "mobile_subscriptions_norm", &infrastructure_HighBest_sigmoid_resultUSA::mobile_subscriptions_norm,
        "mobile_subscriptions_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::mobile_subscriptions_sigmoid,
        "housing_units", &infrastructure_HighBest_sigmoid_resultUSA::housing_units,
        "housing_units_min", &infrastructure_HighBest_sigmoid_resultUSA::housing_units_min,
        "housing_units_max", &infrastructure_HighBest_sigmoid_resultUSA::housing_units_max,
        "housing_units_norm", &infrastructure_HighBest_sigmoid_resultUSA::housing_units_norm,
        "housing_units_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::housing_units_sigmoid,
        "data_centers", &infrastructure_HighBest_sigmoid_resultUSA::data_centers,
        "data_centers_min", &infrastructure_HighBest_sigmoid_resultUSA::data_centers_min,
        "data_centers_max", &infrastructure_HighBest_sigmoid_resultUSA::data_centers_max,
        "data_centers_norm", &infrastructure_HighBest_sigmoid_resultUSA::data_centers_norm,
        "data_centers_sigmoid", &infrastructure_HighBest_sigmoid_resultUSA::data_centers_sigmoid
    );

    lua.new_usertype<education_HighBest_sigmoid_resultUSA>("education_HighBest_sigmoid_resultUSA",
        "literacy_rate", &education_HighBest_sigmoid_resultUSA::literacy_rate,
        "literacy_rate_min", &education_HighBest_sigmoid_resultUSA::literacy_rate_min,
        "literacy_rate_max", &education_HighBest_sigmoid_resultUSA::literacy_rate_max,
        "literacy_rate_norm", &education_HighBest_sigmoid_resultUSA::literacy_rate_norm,
        "literacy_rate_sigmoid", &education_HighBest_sigmoid_resultUSA::literacy_rate_sigmoid,
        "education_spending_pct_gdp", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp,
        "education_spending_pct_gdp_min", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp_min,
        "education_spending_pct_gdp_max", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp_max,
        "education_spending_pct_gdp_norm", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp_norm,
        "education_spending_pct_gdp_sigmoid", &education_HighBest_sigmoid_resultUSA::education_spending_pct_gdp_sigmoid,
        "school_life_expectancy", &education_HighBest_sigmoid_resultUSA::school_life_expectancy,
        "school_life_expectancy_min", &education_HighBest_sigmoid_resultUSA::school_life_expectancy_min,
        "school_life_expectancy_max", &education_HighBest_sigmoid_resultUSA::school_life_expectancy_max,
        "school_life_expectancy_norm", &education_HighBest_sigmoid_resultUSA::school_life_expectancy_norm,
        "school_life_expectancy_sigmoid", &education_HighBest_sigmoid_resultUSA::school_life_expectancy_sigmoid,
        "high_school_graduation_rate", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate,
        "high_school_graduation_rate_min", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate_min,
        "high_school_graduation_rate_max", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate_max,
        "high_school_graduation_rate_norm", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate_norm,
        "high_school_graduation_rate_sigmoid", &education_HighBest_sigmoid_resultUSA::high_school_graduation_rate_sigmoid,
        "tertiary_attainment_pct", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct,
        "tertiary_attainment_pct_min", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct_min,
        "tertiary_attainment_pct_max", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct_max,
        "tertiary_attainment_pct_norm", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct_norm,
        "tertiary_attainment_pct_sigmoid", &education_HighBest_sigmoid_resultUSA::tertiary_attainment_pct_sigmoid,
        "public_school_students", &education_HighBest_sigmoid_resultUSA::public_school_students,
        "public_school_students_min", &education_HighBest_sigmoid_resultUSA::public_school_students_min,
        "public_school_students_max", &education_HighBest_sigmoid_resultUSA::public_school_students_max,
        "public_school_students_norm", &education_HighBest_sigmoid_resultUSA::public_school_students_norm,
        "public_school_students_sigmoid", &education_HighBest_sigmoid_resultUSA::public_school_students_sigmoid,
        "college_students", &education_HighBest_sigmoid_resultUSA::college_students,
        "college_students_min", &education_HighBest_sigmoid_resultUSA::college_students_min,
        "college_students_max", &education_HighBest_sigmoid_resultUSA::college_students_max,
        "college_students_norm", &education_HighBest_sigmoid_resultUSA::college_students_norm,
        "college_students_sigmoid", &education_HighBest_sigmoid_resultUSA::college_students_sigmoid,
        "stem_graduates_yearly", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly,
        "stem_graduates_yearly_min", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly_min,
        "stem_graduates_yearly_max", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly_max,
        "stem_graduates_yearly_norm", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly_norm,
        "stem_graduates_yearly_sigmoid", &education_HighBest_sigmoid_resultUSA::stem_graduates_yearly_sigmoid
    );

    lua.new_usertype<UtilityUSAConfig>("UtilityUSAConfig",
        "country", &UtilityUSAConfig::country,
        "government_sigmoid_result", &UtilityUSAConfig::government_sigmoid_result,
        "demography_highbest_sigmoid_result", &UtilityUSAConfig::demography_highbest_sigmoid_result,
        "demography_lowbest_sigmoid_result", &UtilityUSAConfig::demography_lowbest_sigmoid_result,
        "economy_highbest_sigmoid_result", &UtilityUSAConfig::economy_highbest_sigmoid_result,
        "economy_lowbest_sigmoid_result", &UtilityUSAConfig::economy_lowbest_sigmoid_result,
        "government_highbest_sigmoid_result", &UtilityUSAConfig::government_highbest_sigmoid_result,
        "government_lowbest_sigmoid_result", &UtilityUSAConfig::government_lowbest_sigmoid_result,
        "military_highbest_sigmoid_result", &UtilityUSAConfig::military_highbest_sigmoid_result,
        "resources_highbest_sigmoid_result", &UtilityUSAConfig::resources_highbest_sigmoid_result,
        "resources_lowbest_sigmoid_result", &UtilityUSAConfig::resources_lowbest_sigmoid_result,
        "infrastructure_highbest_sigmoid_result", &UtilityUSAConfig::infrastructure_highbest_sigmoid_result,
        "education_highbest_sigmoid_result", &UtilityUSAConfig::education_highbest_sigmoid_result
    );

    lua.new_usertype<kingdom_infoMagic>("kingdom_infoMagic",
        "name", &kingdom_infoMagic::name,
        "founded_year", &kingdom_infoMagic::founded_year,
        "capital", &kingdom_infoMagic::capital,
        "ruling_house", &kingdom_infoMagic::ruling_house,
        "current_monarch", &kingdom_infoMagic::current_monarch,
        "government_type", &kingdom_infoMagic::government_type
    );

    lua.new_usertype<government_HighBest_sigmoid_resultMagic>("government_HighBest_sigmoid_resultMagic",
        "approval_rating", &government_HighBest_sigmoid_resultMagic::approval_rating,
        "approval_rating_min", &government_HighBest_sigmoid_resultMagic::approval_rating_min,
        "approval_rating_max", &government_HighBest_sigmoid_resultMagic::approval_rating_max,
        "approval_rating_norm", &government_HighBest_sigmoid_resultMagic::approval_rating_norm,
        "approval_rating_sigmoid", &government_HighBest_sigmoid_resultMagic::approval_rating_sigmoid
    );

    lua.new_usertype<government_LowBest_sigmoid_resultMagic>("government_LowBest_sigmoid_resultMagic",
        "tax_burden_index", &government_LowBest_sigmoid_resultMagic::tax_burden_index,
        "tax_burden_index_min", &government_LowBest_sigmoid_resultMagic::tax_burden_index_min,
        "tax_burden_index_max", &government_LowBest_sigmoid_resultMagic::tax_burden_index_max,
        "tax_burden_index_norm", &government_LowBest_sigmoid_resultMagic::tax_burden_index_norm,
        "tax_burden_index_sigmoid", &government_LowBest_sigmoid_resultMagic::tax_burden_index_sigmoid
    );

    lua.new_usertype<magic_HighBest_sigmoid_resultMagic>("magic_HighBest_sigmoid_resultMagic",
        "mana_saturation", &magic_HighBest_sigmoid_resultMagic::mana_saturation,
        "mana_saturation_min", &magic_HighBest_sigmoid_resultMagic::mana_saturation_min,
        "mana_saturation_max", &magic_HighBest_sigmoid_resultMagic::mana_saturation_max,
        "mana_saturation_norm", &magic_HighBest_sigmoid_resultMagic::mana_saturation_norm,
        "mana_saturation_sigmoid", &magic_HighBest_sigmoid_resultMagic::mana_saturation_sigmoid
    );

    lua.new_usertype<magic_LowBest_sigmoid_resultMagic>("magic_LowBest_sigmoid_resultMagic",
        "forbidden_magic_incidents", &magic_LowBest_sigmoid_resultMagic::forbidden_magic_incidents,
        "forbidden_magic_incidents_min", &magic_LowBest_sigmoid_resultMagic::forbidden_magic_incidents_min,
        "forbidden_magic_incidents_max", &magic_LowBest_sigmoid_resultMagic::forbidden_magic_incidents_max,
        "forbidden_magic_incidents_norm", &magic_LowBest_sigmoid_resultMagic::forbidden_magic_incidents_norm,
        "forbidden_magic_incidents_sigmoid", &magic_LowBest_sigmoid_resultMagic::forbidden_magic_incidents_sigmoid
    );

    lua.new_usertype<population_LowBest_sigmoid_resultMagic>("population_LowBest_sigmoid_resultMagic",
        "total_population", &population_LowBest_sigmoid_resultMagic::total_population,
        "total_population_min", &population_LowBest_sigmoid_resultMagic::total_population_min,
        "total_population_max", &population_LowBest_sigmoid_resultMagic::total_population_max,
        "total_population_norm", &population_LowBest_sigmoid_resultMagic::total_population_norm,
        "total_population_sigmoid", &population_LowBest_sigmoid_resultMagic::total_population_sigmoid
    );

}