#pragma once
#include <string>
#include <iostream>
 //structName countryUSA
struct countryUSA {
    std::string country_name = "UnitedStates";
    int year = 2025;
    std::string capital = "WashingtonDC";
    std::string currency = "USD";
    int states = 50;
    float states_min = 0.0f;
    float states_max = 100.0f;
    float states_norm = 0.5f;
    float states_sigmoid = 0.6225f;
    int territories = 5;
    float territories_min = 0.0f;
    float territories_max = 20.0f;
    float territories_norm = 0.25f;
    float territories_sigmoid = 0.5622f;
    int time_zones = 6;
    float time_zones_min = 1.0f;
    float time_zones_max = 24.0f;
    float time_zones_norm = 0.2174f;
    float time_zones_sigmoid = 0.5541f;
};
 //structName resources_HighBest_sigmoid_result_Part02USA
struct resources_HighBest_sigmoid_result_Part02USA {
    float farmland_million_acres = 876.00;
    float farmland_million_acres_min = 0.0f;
    float farmland_million_acres_max = 2000.0f;
    float farmland_million_acres_norm = 0.438f;
    float farmland_million_acres_sigmoid = 0.6078f;
};
 //structName resources_LowBest_sigmoid_resultUSA
struct resources_LowBest_sigmoid_resultUSA {
    float freshwater_withdrawal_bcm = 444.00;
    float freshwater_withdrawal_bcm_min = 0.0f;
    float freshwater_withdrawal_bcm_max = 2000.0f;
    float freshwater_withdrawal_bcm_norm = 0.222f;
    float freshwater_withdrawal_bcm_sigmoid = 0.5553f;
    float co2_emissions_mt = 4800.00;
    float co2_emissions_mt_min = 0.0f;
    float co2_emissions_mt_max = 15000.0f;
    float co2_emissions_mt_norm = 0.32f;
    float co2_emissions_mt_sigmoid = 0.5793f;
};
 //structName infrastructure_HighBest_sigmoid_result_Part01USA
struct infrastructure_HighBest_sigmoid_result_Part01USA {
    int land_area_km2 = 9147420;
    float land_area_km2_min = 0.0f;
    float land_area_km2_max = 20000000.0f;
    float land_area_km2_norm = 0.4574f;
    float land_area_km2_sigmoid = 0.6124f;
    int total_area_km2 = 9833517;
    float total_area_km2_min = 0.0f;
    float total_area_km2_max = 20000000.0f;
    float total_area_km2_norm = 0.4917f;
    float total_area_km2_sigmoid = 0.6205f;
    int coastline_km = 19924;
    float coastline_km_min = 0.0f;
    float coastline_km_max = 100000.0f;
    float coastline_km_norm = 0.1992f;
    float coastline_km_sigmoid = 0.5496f;
    int road_km = 6830000;
    float road_km_min = 0.0f;
    float road_km_max = 20000000.0f;
    float road_km_norm = 0.3415f;
    float road_km_sigmoid = 0.5846f;
    int rail_km = 148553;
    float rail_km_min = 0.0f;
    float rail_km_max = 500000.0f;
    float rail_km_norm = 0.2971f;
    float rail_km_sigmoid = 0.5737f;
    int airports = 19500;
    float airports_min = 0.0f;
    float airports_max = 50000.0f;
    float airports_norm = 0.39f;
    float airports_sigmoid = 0.5963f;
    int major_ports = 360;
    float major_ports_min = 0.0f;
    float major_ports_max = 2000.0f;
    float major_ports_norm = 0.18f;
    float major_ports_sigmoid = 0.5449f;
    float electricity_access_pct = 100.00;
    float electricity_access_pct_min = 0.0f;
    float electricity_access_pct_max = 100.0f;
    float electricity_access_pct_norm = 1.0f;
    float electricity_access_pct_sigmoid = 0.7311f;
    float safe_water_access_pct = 99.00;
    float safe_water_access_pct_min = 0.0f;
    float safe_water_access_pct_max = 100.0f;
    float safe_water_access_pct_norm = 0.99f;
    float safe_water_access_pct_sigmoid = 0.7291f;
    int fixed_broadband_subscriptions = 123000000;
    float fixed_broadband_subscriptions_min = 0.0f;
    float fixed_broadband_subscriptions_max = 500000000.0f;
    float fixed_broadband_subscriptions_norm = 0.246f;
    float fixed_broadband_subscriptions_sigmoid = 0.5612f;
};
 //structName infrastructure_HighBest_sigmoid_result_Part02USA
struct infrastructure_HighBest_sigmoid_result_Part02USA {
    int mobile_subscriptions = 386000000;
    float mobile_subscriptions_min = 0.0f;
    float mobile_subscriptions_max = 1000000000.0f;
    float mobile_subscriptions_norm = 0.386f;
    float mobile_subscriptions_sigmoid = 0.5953f;
    int housing_units = 146000000;
    float housing_units_min = 0.0f;
    float housing_units_max = 500000000.0f;
    float housing_units_norm = 0.292f;
    float housing_units_sigmoid = 0.5725f;
    int data_centers = 5400;
    float data_centers_min = 0.0f;
    float data_centers_max = 20000.0f;
    float data_centers_norm = 0.27f;
    float data_centers_sigmoid = 0.5671f;
};
 //structName education_HighBest_sigmoid_resultUSA
struct education_HighBest_sigmoid_resultUSA {
    float literacy_rate = 99.00;
    float literacy_rate_min = 0.0f;
    float literacy_rate_max = 100.0f;
    float literacy_rate_norm = 0.99f;
    float literacy_rate_sigmoid = 0.7291f;
    float education_spending_pct_gdp = 5.00;
    float education_spending_pct_gdp_min = 0.0f;
    float education_spending_pct_gdp_max = 20.0f;
    float education_spending_pct_gdp_norm = 0.25f;
    float education_spending_pct_gdp_sigmoid = 0.5622f;
    float school_life_expectancy = 16.00;
    float school_life_expectancy_min = 0.0f;
    float school_life_expectancy_max = 25.0f;
    float school_life_expectancy_norm = 0.64f;
    float school_life_expectancy_sigmoid = 0.6548f;
    float high_school_graduation_rate = 87.00;
    float high_school_graduation_rate_min = 0.0f;
    float high_school_graduation_rate_max = 100.0f;
    float high_school_graduation_rate_norm = 0.87f;
    float high_school_graduation_rate_sigmoid = 0.7047f;
    float tertiary_attainment_pct = 54.00;
    float tertiary_attainment_pct_min = 0.0f;
    float tertiary_attainment_pct_max = 100.0f;
    float tertiary_attainment_pct_norm = 0.54f;
    float tertiary_attainment_pct_sigmoid = 0.6318f;
    int public_school_students = 49800000;
    float public_school_students_min = 0.0f;
    float public_school_students_max = 150000000.0f;
    float public_school_students_norm = 0.332f;
    float public_school_students_sigmoid = 0.5822f;
    int college_students = 18900000;
    float college_students_min = 0.0f;
    float college_students_max = 50000000.0f;
    float college_students_norm = 0.378f;
    float college_students_sigmoid = 0.5934f;
    int stem_graduates_yearly = 820000;
    float stem_graduates_yearly_min = 0.0f;
    float stem_graduates_yearly_max = 5000000.0f;
    float stem_graduates_yearly_norm = 0.164f;
    float stem_graduates_yearly_sigmoid = 0.5409f;
};
 //structName health_HighBest_sigmoid_resultUSA
struct health_HighBest_sigmoid_resultUSA {
    float health_spending_pct_gdp = 17.30;
    float health_spending_pct_gdp_min = 0.0f;
    float health_spending_pct_gdp_max = 40.0f;
    float health_spending_pct_gdp_norm = 0.4325f;
    float health_spending_pct_gdp_sigmoid = 0.6065f;
    float insured_rate = 92.00;
    float insured_rate_min = 0.0f;
    float insured_rate_max = 100.0f;
    float insured_rate_norm = 0.92f;
    float insured_rate_sigmoid = 0.715f;
    float physicians_per_1000 = 2.70;
    float physicians_per_1000_min = 0.0f;
    float physicians_per_1000_max = 15.0f;
    float physicians_per_1000_norm = 0.18f;
    float physicians_per_1000_sigmoid = 0.5449f;
    float hospital_beds_per_1000 = 2.80;
    float hospital_beds_per_1000_min = 0.0f;
    float hospital_beds_per_1000_max = 20.0f;
    float hospital_beds_per_1000_norm = 0.14f;
    float hospital_beds_per_1000_sigmoid = 0.5349f;
    int nurses = 5200000;
    float nurses_min = 0.0f;
    float nurses_max = 15000000.0f;
    float nurses_norm = 0.3467f;
    float nurses_sigmoid = 0.5858f;
    int hospital_count = 6093;
    float hospital_count_min = 0.0f;
    float hospital_count_max = 20000.0f;
    float hospital_count_norm = 0.3046f;
    float hospital_count_sigmoid = 0.5756f;
};
 //structName health_LowBest_sigmoid_resultUSA
struct health_LowBest_sigmoid_resultUSA {
    float obesity_rate = 40.30;
    float obesity_rate_min = 0.0f;
    float obesity_rate_max = 100.0f;
    float obesity_rate_norm = 0.403f;
    float obesity_rate_sigmoid = 0.5994f;
    float maternal_mortality = 22.30;
    float maternal_mortality_min = 0.0f;
    float maternal_mortality_max = 200.0f;
    float maternal_mortality_norm = 0.1115f;
    float maternal_mortality_sigmoid = 0.5278f;
};
 //structName technology_HighBest_sigmoid_resultUSA
struct technology_HighBest_sigmoid_resultUSA {
    double rnd_spending = 940000000000;
    float rnd_spending_min = 0.0f;
    float rnd_spending_max = 3000000000000.0f;
    float rnd_spending_norm = 0.3133f;
    float rnd_spending_sigmoid = 0.5777f;
    float rnd_share_gdp = 3.40;
    float rnd_share_gdp_min = 0.0f;
    float rnd_share_gdp_max = 15.0f;
    float rnd_share_gdp_norm = 0.2267f;
    float rnd_share_gdp_sigmoid = 0.5564f;
    float internet_users_pct = 97.10;
    float internet_users_pct_min = 0.0f;
    float internet_users_pct_max = 100.0f;
    float internet_users_pct_norm = 0.971f;
    float internet_users_pct_sigmoid = 0.7253f;
    float smartphone_users_pct = 90.00;
    float smartphone_users_pct_min = 0.0f;
    float smartphone_users_pct_max = 100.0f;
    float smartphone_users_pct_norm = 0.9f;
    float smartphone_users_pct_sigmoid = 0.7109f;
    double cloud_market_size = 400000000000;
    float cloud_market_size_min = 0.0f;
    float cloud_market_size_max = 2000000000000.0f;
    float cloud_market_size_norm = 0.2f;
    float cloud_market_size_sigmoid = 0.5498f;
    double ai_private_investment = 67000000000;
    float ai_private_investment_min = 0.0f;
    float ai_private_investment_max = 500000000000.0f;
    float ai_private_investment_norm = 0.134f;
    float ai_private_investment_sigmoid = 0.5334f;
    int space_launches_yearly = 154;
    float space_launches_yearly_min = 0.0f;
    float space_launches_yearly_max = 1000.0f;
    float space_launches_yearly_norm = 0.154f;
    float space_launches_yearly_sigmoid = 0.5384f;
    int patents_granted_yearly = 323410;
    float patents_granted_yearly_min = 0.0f;
    float patents_granted_yearly_max = 1000000.0f;
    float patents_granted_yearly_norm = 0.3234f;
    float patents_granted_yearly_sigmoid = 0.5802f;
};
struct UtilityUSAConfig {
    countryUSA country; 
    resources_HighBest_sigmoid_result_Part02USA resources_highbest_sigmoid_result_part02; 
    resources_LowBest_sigmoid_resultUSA resources_lowbest_sigmoid_result; 
    infrastructure_HighBest_sigmoid_result_Part01USA infrastructure_highbest_sigmoid_result_part01; 
    infrastructure_HighBest_sigmoid_result_Part02USA infrastructure_highbest_sigmoid_result_part02; 
    education_HighBest_sigmoid_resultUSA education_highbest_sigmoid_result; 
    health_HighBest_sigmoid_resultUSA health_highbest_sigmoid_result; 
    health_LowBest_sigmoid_resultUSA health_lowbest_sigmoid_result; 
    technology_HighBest_sigmoid_resultUSA technology_highbest_sigmoid_result; 
};

